#!/usr/bin/env python3
"""Генерація wiring/pinout PNG для ARDUINO-Reference. Оригінальні схеми, без копійованих картинок."""
import os
from PIL import Image, ImageDraw, ImageFont

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "img")
FB = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FM = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

def fonts():
    return (ImageFont.truetype(FB, 40), ImageFont.truetype(FB, 24),
            ImageFont.truetype(FM, 22), ImageFont.truetype(FR, 20))

# name: (заголовок, [рядки схеми])
C = {
"platformio-flow-scheme.png": ("PlatformIO - ini, build, upload",
 ["platformio.ini: плата і фреймворк",
  "lib_deps: бібліотеки з версіями",
  "Build: компіляція без сюрпризів",
  "Upload + Monitor: прошивка і лог"]),
"ard-rp2040-voltages-scheme.png": ("RP2040 - 3V3 і PIO",
 ["3V3 логіка, 5V вбиває пін",
  "BOOTSEL: затиснути при старті",
  "PIO-автомати: точні протоколи",
  "Arduino-core або MicroPython"]),
"arduino-howto-map-scheme.png": ("Карта довідника — куди йти",
 ["Home — вхід", "Розділи 00–99 — теми",
  "Нота: призначення → код → помилки", "Не знайшов за 5 хв — пошук!"]),
"arduino-glossary-terms-scheme.png": ("Словник Arduino — шари і терміни",
 ["Скетч — setup плюс loop", "Бібліотеки через менеджер",
  "Bootloader шиє по USB", "VIN 7-12 В, не 5!"]),
"arduino-families-compare-scheme.png": ("Плати Arduino — вибір",
 ["Uno — класика навчання", "Nano — компактно",
  "Mega — багато ніг", "Uno R4 — сучасний 32-біт"]),
"arduino-devkit-boards-scheme.png": ("Плати — Uno / Nano / Mega",
 ["Uno з коробки вчить", "Nano в макетку стає",
  "Клони: драйвер CH340!", "Живлення 7-12 В на VIN"]),
"arduino-env-choose-scheme.png": ("Середовище — IDE / CLI",
 ["IDE 2 — старт за вечір", "CLI — автоматизація і CI",
  "Бібліотеки з реєстру", "Приклади з кожного пакета"]),
"arduino-adc-scheme.png": ("АЦП 10 біт — вимір",
 ["0-1023 це 0-5 В!", "Опора: 5V або 1.1V внутр!", "Усереднення 64 рази", "Дільник для високого!"]),
"arduino-dac-nema-scheme.png": ("ЦАП нема — обхід",
 ["AVR без ЦАП взагалі!", "ШІМ плюс RC дає рівень", "MCP4725 по I2C", "Due має 2 ЦАП!"]),
"arduino-timeri-scheme.png": ("Таймери — час",
 ["millis замість delay!", "Timer1 16 біт точний", "Tone краде таймер", "Servo свої ноги"]),
"arduino-son-wdt-scheme.png": ("Сон і WDT — економія",
 ["WDT будить з сну", "Все вимкнути перед сном!", "Будильник або кнопка", "Міліампери в мікроампери"]),
"arduino-vin-power-scheme.png": ("Живлення — VIN і USB",
 ["VIN 7-12 В, не 5!", "USB 5 В напряму", "LDO гріється на струмі", "Джек 2.1 мм центр плюс"]),
"arduino-battery-scheme.png": ("Батарейки — автономність",
 ["Крона на день-два", "Li-Ion плюс захист", "Сон між вимірами!", "Сонячна з запасом"]),"arduino-mpu-scheme.png": ("MPU6050 — рух",
 ["Бібліотека MPU6050_light", "Калібрування в спокої!", "DMP або комплементарний", "Вібрації брешуть"]),
"arduino-mq-scheme.png": ("MQ-гази — пороги",
 ["Прогрів доба!", "Ro на вулиці", "Пороги а не ppm", "Нагрівач їсть струм"]),
"arduino-rfid2-scheme.png": ("RC522 — картки",
 ["Тільки 3.3В!", "Бібліотека MFRC522", "UID не пароль", "Антена вільна"]),
"arduino-enc-scheme.png": ("Енкодер — кроки",
 ["Переривання на канал!", "Volatile лічильник", "Дребезг фільтром", "Напрям з фази"]),"arduino-dht-ds-scheme.png": ("DHT і DS18B20 — температура",
 ["Бібліотеки роблять все!", "DHT опитуй рідко", "DS18B20: шина і CRC", "Підтяжка 4.7к!"]),
"arduino-bme-scheme.png": ("BME280 — клімат",
 ["Адреса джампером SDO!", "Бібліотека Adafruit", "Висота з тиску", "5V толерантний? Ні!"]),
"arduino-hcsr-pir-scheme.png": ("Дистанція і рух",
 ["Trig 10 мкс, echo міряй", "PIR гріється хвилину!", "Лінза Френеля ширше бачить"]),
"arduino-lm35-ntc-scheme.png": ("Аналогові датчики",
 ["LM35: 10 мВ на градус", "NTC: дільник плюс таблиця", "Опора 1.1В точніше!", "Усереднення!"]),
"arduino-lcd1602-scheme.png": ("LCD1602 — символи",
 ["I2C-рюкзак економить ноги!", "Контраст крутилкою", "Адреса 0x27 або 0x3F", "Підсвітку не забудь"]),
"arduino-tft-scheme.png": ("TFT — колір",
 ["Бібліотеки Adafruit ST7735", "DC пін окремо!", "SPI швидко", "Буфер малий — смугами"]),
"arduino-motor-scheme.png": ("Серво і мотори — сила",
 ["Серво: бібліотека плюс живлення", "L298N окремо живи!", "Діоди від викидів", "ШІМ на EN для швидкості"]),"arduino-oled-scheme.png": ("OLED — графіка",
 ["Бібліотеки Adafruit/U8g2", "Буфер в RAM!", "I2C вистачає", "Яскравість палить"]),
"arduino-neo-servo-scheme.png": ("Стрічки і серво",
 ["NeoPixel: один пін!", "Живлення окремо!", "Серво: бібліотека Servo", "Реле через транзистор!"]),
"arduino-esp01-scheme.png": ("ESP-01 — WiFi поруч",
 ["AT-прошивка з коробки", "Живлення 3.3В і струм!", "CH_PD на живлення", "Бод 115200 стабільно"]),
"arduino-gps-scheme.png": ("GPS NEO — координати",
 ["NMEA 9600 з коробки", "Антена з видом на небо!", "Холодний старт хвилини", "PPS для точного часу"]),"arduino-nrf24-scheme.png": ("NRF24 — радіо",
 ["Труби і адреси", "Живлення 3.3В!", "Конденсатор на модуль", "Канал подалі від WiFi"]),
"arduino-rc522-scheme.png": ("RC522 — картки",
 ["Тільки 3.3В!", "UID не пароль!", "Бібліотека MFRC522", "Антена вільна"]),
"arduino-shield-scheme.png": ("Шилди — поверхи",
 ["Став зверху, піни наскрізні", "Конфлікт пінів дивись!", "Мотор-шилд окремо живи"]),
"arduino-klon-scheme.png": ("Клони — ціна і ризик",
 ["CH340 драйвер став!", "LDO слабкий", "USB іноді тільки живлення", "Перевіряй відгуки"]),"arduino-lora-scheme.png": ("LoRa — далеко",
 ["SF/BW однакові з боків!", "Антена на свій діапазон", "Живлення 3.3В!", "рідко і коротко"]),
"arduino-gsm-scheme.png": ("GSM SIM800 — мережа",
 ["Живлення 2А піки!", "AT-команди повільно", "Антена надворі", "Баланс SIM!"]),
"arduino-memory-scheme.png": ("Память — мало!",
 ["Flash 32К код", "SRAM 2К дані!", "EEPROM 1К налаштування", "PROGMEM для текстів"]),
"arduino-buck-scheme.png": ("DC-DC — живлення",
 ["Вхід вище виходу", "Дросель з запасом", "ККД міряй!", "Шум далі від АЦП"]),
"arduino-level-scheme.png": ("Рівні 5В і 3.3В — міст",
 ["Дільник тільки вхід!", "MOSFET обидва боки", "TXS для шин", "Земля спільна!"]),
"arduino-modbus-scheme.png": ("Modbus — регістри",
 ["Адреса плюс CRC!", "DE вчасно", "Швидкість однакова", "Термінація 120 Ом"]),
"arduino-mqtt-esp-scheme.png": ("MQTT через ESP — хмара",
 ["ESP як WiFi-модем", "AT або прошивка-шлюз", "QoS 0 для телеметрії", "LWT про смерть"]),
"arduino-tracker-scheme.png": ("Трекер — координати",
 ["GPS плюс GSM разом", "Живлення 2А піки!", "Сон між точками", "Антенам видно небо"]),
"arduino-logger-scheme.png": ("Логер — запис на SD",
 ["Буфер переживає паузи", "Файл щодоби новий", "RTC мітить час", "Живий перегляд по USB"]),"arduino-meteo-scheme.png": ("Метеостанція — вузол",
 ["Датчики плюс сон", "Живлення з запасом", "Лог на SD", "Корпус з вентиляцією"]),
"arduino-smart-scheme.png": ("Розумний дім — вузол",
 ["Реле через транзистор!", "Кнопки з дребезгом", "Статуси в EEPROM", "Ручне керування дублює"]),
"arduino-tools-scheme.png": ("Прилади — міряй",
 ["Мультиметр першим!", "Осцилограф на ШІМ", "Логіка на шини", "БЖ з обмеженням"]),
"arduino-maketka-scheme.png": ("Макетка — межі",
 ["I2C коротко!", "Живлення bulk", "Довгі дроти гальмують", "Далі паяна плата!"]),
"arduino-diagmap-scheme.png": ("Карта діагностики — маршрут",
 ["Лог і Blink першими!", "Порт плюс кабель", "Живлення мультиметром", "Шини сканером"]),"arduino-faq-scheme.png": ("FAQ — діагностика",
 ["Симптом плюс причина", "Міряй не гадай!", "Мінімум коду"]),
"arduino-checklist-scheme.png": ("Чеклісти — запуск",
 ["Живлення плюс конект", "Blink першим!", "Кожен пункт галочкою"]),"arduino-digital-scheme.png": ("Цифрові піни — режими",
 ["pinMode: INPUT OUTPUT PULLUP", "Пиши HIGH LOW, читай так само", "Внутрішня підтяжка економить резистор!",
  "Струм піна до 20 мА!"]),
"arduino-pwm-scheme.png": ("ШІМ — analogWrite",
 ["Не аналог, а шпаруватість!", "490 Гц або 980 Гц за таймером", "Tone на buzzer окремо",
  "RC-фільтр робить ЦАП"]),
"arduino-interrupt-scheme.png": ("Переривання — події",
 ["attachInterrupt: RISING FALLING CHANGE", "В ISR тільки прапорець!", "Volatile для спільних!",
  "Дребезг давити часом"]),
"arduino-uart-scheme.png": ("UART — Serial і софт",
 ["Baud однаковий з обох боків!", "SoftwareSerial повільний", "D0/D1 зайняті USB!",
  "RS485 через DE-пін"]),
"arduino-spi-scheme.png": ("SPI — швидко",
 ["SCK MOSI MISO плюс SS", "Кожному CS свій пін!", "Дільник швидкості", "Довгі дроти гальмують"]),
"arduino-i2c-wire-scheme.png": ("I2C — Wire",
 ["Сканер знаходить адреси", "Підтяжки 4.7к обовязкові!", "100 кГц для старту", "Довжина до метра"]),"uno-power-scheme.png": ("Uno — живлення і прошивка",
 ["USB 5V або VIN 7-12 В", "LDO робить 5 В і 3.3 В",
  "ATmega328P: 32 КБ Flash", "Reset-кнопка + ICSP"]),
"arduino-uno-r3-scheme.png": ("Uno R3 — класика",
 ["ATmega328P: 32 КБ Flash", "USB-B через ATmega16U2", "VIN 7-12 В, не 5!",
  "ICSP для прямого ISP"]),
"arduino-nano-mega-scheme.png": ("Nano і Mega — ноги",
 ["Nano в макетку стає", "Mega: 54 ноги, 4 UART", "D0/D1 зайняті USB!",
  "CH340 драйвер на клонах"]),
"arduino-due-zero-scheme.png": ("Due і Zero — ARM",
 ["3.3 В логіка, не 5!", "Due: 84 МГц SAM3X", "Zero: налагодження EDBG",
  "5V шилди через узгодження!"]),
"arduino-uno-r4-scheme.png": ("Uno R4 — Renesas",
 ["Minima без WiFi, WiFi з ESP32-S3", "32-біт RA4M1", "5V сумісність збережено!",
  "Матриця 12x8 на WiFi"]),
"arduino-ide-cli-scheme.png": ("IDE і CLI — збірка",
 ["IDE 2: старт за вечір", "CLI: те саме в консолі", "FQBN вибирає плату!",
  "CI збирає приклади"]),
"arduino-bootloader-scheme.png": ("Bootloader і avrdude",
 ["Кнопка не потрібна — авторесет", "Fuse біти: двічі міряй!", "ISP коли bootloader мертвий",
  "Бекап fuse перед змінами"]),"nano-pinout-scheme.png": ("Nano — піни і макетка",
 ["30 ніг у макетку", "A0-A7 аналог", "D0/D1 — UART для USB!",
  "RST на землю — ресет"]),
"ard-nano33-scheme.png": ("Arduino-ARM: 32-біт",
 ["Nano 33 BLE: nRF52832 M4, RAM 512 КБ",
  "MKR1000: LTE-M/NB, SAMW25 M4",
  "Portenta H7: M7 480 МГц, EtherCAT",
  "3.3 В логіка — модулі 5 В з рівнів!",
  "Core: поверх mbed RTOS (Nano 33)",
  "Cloud/Edge: логіка на платі, sync у хмарі"]),
"ard-timers16-scheme.png": ("ATmega таймери: 16-біт",
 ["Timer1: D9/D10 (OC1A/OC1B), ICP1 = D8",
  "WGM14 CTC: TOP = OCR1A, 16-біт PWM",
  "D5/D6 — 8-бітний PWM (Timer0), D3/D11 — T2",
  "Timer0: millis() — не чіпай! /64",
  "Ділиміти /16 МГц: /1 — 3874 Гц, /8 — 484 Гц",
  "ICP1: зовнішній PWM, mode 15 + TINS"]),
"ard-tft-touch-deep-scheme.png": ("TFT з тачем глибоко",
 ["ILI9341 320x240, 2.8-3.5\"",
  "XPT2046: калібрування 3 точки",
  "SPI 40 МГц, затримка 0 мкс",
  "Частковий буфер для RAM",
  "Подвійна буферизація для плавності"]),
"ard-nextion-hmi-scheme.png": ("Nextion HMI-редактор",
 ["Редактор .tft, SD-картка",
  "Команди текстом + FF FF FF",
  "Події кнопок — в Arduino",
  "Тач — матриця калібрування",
  "Дисплей з підсвічуванням"]),
"ard-sd-fatfs-deep-scheme.png": ("SD-FATFS глибоко",
 ["FAT32 з файлами 8.3", "Ротація 10 файлів", "Flush перед сном", "Порівняння з носіями"]),
"ard-ethernet-w5500-deep-scheme.png": ("Ethernet-шилд W5500 глибоко",
 ["W5500 8 сокетів у залізі",
  "SPI 40 МГц, CS D10!",
  "SD-слот для сторінок",
  "Веб-сервер :80",
  "MQTT через сокет"]),
"ard-gsm-deep-http-scheme.png": ("GSM глибоко: HTTP з SIM",
 ["SIM800C 4V 3A окремо",
  "AT-команди 9600 8N1",
  "HTTP-GET з SMS резервом",
  "IoT-тариф для SIM",
  "USB-лог для AT-діагностики"]),
"ard-usb-host-scheme.png": ("AVR-USB: ATmega32U4",
 ["Leonardo / Pro Micro: USB в кристалі",
  "Serial = CDC, Serial1 = HW UART",
  "D+ 1.5 кОм → 3.3 В (FS declaration)",
  "100 мА до SET_CONFIGURATION, далі 500",
  "HID: клавіатура без драйверів",
  "Pro Micro: логіка 3.3 В! не 5 В!"]),
"ard-svitlo-tisk-tof-scheme.png": ("Світло + тиск + ToF",
 ["BH1750 0x23: люкси / 1.2",
  "BMP280 0x76: dig-коефіцієнти!",
  "VL53L0X 0x29: XSHUT до VCC",
  "Підтяжки 4.7 кОм до 3.3 В!",
  "Модулі GY: живлення 5 В",
  "Шина до 30 см на 100 кГц"]),
"ard-strum-ina219-scheme.png": ("Струм: INA219 + ACS712",
 ["INA219: регістр калібрування!",
  "ACS712: нуль = VCC/2",
  "Версії 5/20/30 А: 185/100/66",
  "Усереднення 64 без min/max",
  "Ампер-години + EEPROM щогодини",
  "220 В тільки через PZEM+CT!"]),
"ard-co2-povitrya-scheme.png": ("CO2 + VOC повітря",
 ["MH-Z19B: кадр FF 86, чексума!",
  "BME680: heater 320 градусів",
  "Прогрів 3 хв, дані викинути",
  "Пороги 800/1200/2000 ppm",
  "Гістерезис реле 800/650",
  "ABC вимкнути в спальні!"]),
"ard-bt-ethernet-scheme.png": ("HC-05 + Ethernet-шилд",
 ["HC-05: AT на 38400 з KEY",
  "W5100: MAC зі стікера, DHCP",
  "D10 — CS шилда, BT на D7/D8!",
  "Шилд + Uno: БЖ 9 В, не USB",
  "Протокол BT: текст + новий рядок",
  "iPhone: тільки BLE, не SPP"]),
"ard-indikatsiya-audio-scheme.png": ("MAX7219 + TM1637 + DFPlayer",
 ["MAX7219: shutdown(0,false)!",
  "TM1637: CLK/DIO, яскравість 0-7",
  "DFPlayer: файли 0001.mp3, FAT32",
  "SPK мінус НЕ земля!",
  "BUSY чекати перед пуском",
  "5 В 1 А окремо + 1000 мкФ"]),
"ard-nano-giga-scheme.png": ("Nano ESP32 + GIGA R1",
 ["Nano ESP32: S3 + USB-C, 3.3 В!",
  "GIGA R1: H747 M7+M4, дисплей",
  "RGB замість звичайного LED",
  "#ifdef на обидві плати",
  "5 В шилди через шифтер",
  "Cloud: Thing + згенерований код"]),
"ard-http-web-scheme.png": ("HTTP-клієнт Arduino",
 ["Host + Content-Length точно!",
  "HTTP/1.0 закриває сам",
  "client.stop() після запиту!",
  "JSON вручну, числа без лапок",
  "W5100: HTTPS нема принципово",
  "Токени в secrets.h, не в git"]),
"ard-mag-gesture-rtc-scheme.png": ("Компас + жести + RTC",
 ["QMC5883L: вісімка 30 с",
  "AD0 MPU в HIGH: 0x69, не 0x68!",
  "APDS-9960: скло ІЧ-прозоре",
  "DS3231: час з комп'ютера раз",
  "Схилення +7 градусів у коді",
  "GPS PPS звіряє RTC"]),
}

def draw(name, title, lines):
    Ft, Fs, Fm, Ff = fonts()
    W, H = 1000, 200 + len(lines) * 44 + 120
    H = max(H, 520)
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, W, 130], fill=(0, 130, 130))
    d.text((30, 22), "ARDUINO-Reference", font=Fs, fill=(255, 255, 255))
    d.text((30, 55), title, font=Ft, fill="white")
    y = 150
    d.rectangle([0, y - 34, W, y + 2], fill=(255, 251, 235))
    d.text((30, y - 30), "5V logika! 3.3V moduli — cherez uzgodzhennia.", font=Ff, fill=(146, 64, 14))
    y += 30
    for ln in lines:
        d.text((30, y), "•  " + ln, font=Fm, fill=(17, 24, 39))
        y += 44
    d.rectangle([0, H - 56, W, H], fill=(241, 245, 249))
    d.text((30, H - 42), "ARDUINO-Reference  •  zgenerovano lokalno (bez kopiiovanykh kartynok)",
           font=Ff, fill=(100, 116, 139))
    img.save(os.path.join(OUT, name))

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for n, (t, ls) in C.items():
        draw(n, t, ls)
    print(f"generated {len(C)} png")
