#!/usr/bin/env python3
"""Генерація wiring/pinout PNG для ESP32-Reference. Оригінальні схеми, без копійованих картинок."""
import os
from PIL import Image, ImageDraw, ImageFont

OUT = "/home/ksalab/projects/.memories/ESP32-Reference/assets/img"
FB = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FM = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

def fonts():
    return (ImageFont.truetype(FB, 40), ImageFont.truetype(FB, 24),
            ImageFont.truetype(FM, 22), ImageFont.truetype(FR, 20))

# name: (заголовок, [рядки схеми])
C = {
"rc522-scheme.png": ("RC522 RFID — SPI, ТІЛЬКИ 3.3V",
 ["ESP32 3V3 ──► VCC (НЕ 5V! вб'є модуль)", "GND ─── GND (спільна)",
  "GPIO18 ──► SCK (VSPI clock)", "GPIO23 ──► MOSI", "GPIO19 ──► MISO",
  "GPIO5 ──► SDA/SS (Chip Select)", "GPIO22 ──► RST (тримати HIGH)",
  "IRQ ──► (можна не підключати, open-drain)"]),
"nrf24-wiring.png": ("NRF24L01 — SPI + конденсатор!",
 ["3V3 ──► VCC через конд. 10–100мкФ (біля модуля!)", "GND ─── GND",
  "GPIO18 SCK / GPIO23 MOSI / GPIO19 MISO", "GPIO5 ──► CSN   GPIO21 ──► CE",
  "IRQ ──► (опційно)   PA+LNA: струм до 250мА!", "Дроти < 20см, окреме живлення для PA"]),
"lora-ra02-scheme.png": ("LoRa Ra-02 SX1276 — АНТЕНА ОБОВ'ЯЗКОВА",
 ["3V3 ──► VCC   GND ─── GND", "SCK/MOSI/MISO ──► GPIO18/23/19",
  "GPIO5 ──► NSS   GPIO25 ──► RST   GPIO26 ──► DIO0",
  "!!! Без антени НЕ вмикати — згорить вихід !!!", "Частота: 433 або 868 МГц (одна!)", "Антена подалі від металу"]),
"sim800l-power-4v.png": ("SIM800L — 4.0V / 2A пік!",
 ["LM2596 виставити 4.0V БЕЗ модуля", "LM2596+ ──► VCC через конд. 1000мкФ",
  "Товсті короткі дроти (пік 2A!)", "GPIO16 ──► SIM RXD (через 1к)",
  "GPIO17 ──► SIM TXD (перехресно)", "GND спільна. НЕ 5V і НЕ 3.3V!"]),
"neo6m-uart.png": ("NEO-6M GPS — UART",
 ["3V3/5V ──► VCC (модуль з LDO)", "GND ─── GND", "GPS TX ──► GPIO16 (RX2)",
  "GPS RX ──► GPIO17 (TX2)", "PPS ──► GPIO (1Гц мітка)", "Антена — вид неба!"]),
"max485-de-re.png": ("MAX485 RS485 — напівдуплекс",
 ["3V3/5V ──► VCC   GND ─── GND", "GPIO17 ──► DI (TX)", "GPIO16 ──► RO (RX)",
  "GPIO4 ──► DE + RE (з'єднати! HIGH=TX)", "A/B ──► вита пара до A/B вузлів",
  "Термінатор 120 Ом на кінцях шини"]),
"can-hvd230-bus.png": ("SN65HVD230 CAN — шина",
 ["3V3 ──► VCC   GND ─── GND", "GPIO21 ──► CTX   GPIO22 ──► CRX",
  "CANH/CANL ──► CANH/CANL шини", "2×120 Ом на кінцях", "Rs: 10к на GND (швидкість)"]),
"lan8720-rmii.png": ("LAN8720 Ethernet — ТІЛЬКИ classic ESP32",
 ["RMII: TX0/TX1/TX_EN/RX0/RX1/CRS_DV", "MDC/MDIO ──► керування PHY",
  "nRST ──► GPIO, кварц 50МГц на платі", "Живлення 3.3V 200мА+", "Не працює на S2/S3/C3!"]),
"ov2640-s3-dvp.png": ("OV2640 камера — S3 + PSRAM",
 ["D0–D7 ──► GPIO камери S3", "VSYNC/HREF/PCLK ──► sync", "SIOC/SIOD ──► SCCB (I2C)",
  "XCLK ──► тактування   PWDN/RESET ──► GPIO", "Без PSRAM тільки QVGA!"]),
"dht22-scheme.png": ("DHT22 — 1-Wire + pull-up",
 ["3V3 ──► VCC   GND ─── GND", "GPIO4 ──► DATA через pull-up 5–10к до VCC",
  "Модулі 3-pin: pull-up вже є", "Опитування раз на 2с (DHT22)"]),
"ds18b20-1wire.png": ("DS18B20 — шина 1-Wire",
 ["3V3 ──► VDD (НЕ паразитне!)", "GND ─── GND", "GPIO15 ──► DQ + pull-up 4.7к",
  "Кілька датчиків на одній лінії DQ", "Довжина: вита пара, 100нФ біля датчика"]),
"bme280-i2c.png": ("BME280 — I2C 0x76/0x77",
 ["3V3 ──► VIN   GND ─── GND", "GPIO22 ──► SCL + pull-up 4.7к",
  "GPIO21 ──► SDA + pull-up 4.7к", "SDO→GND = 0x76, SDO→VCC = 0x77",
  "CSB→VCC в I2C-режимі"]),
"mpu6050-i2c.png": ("MPU6050 — акселерометр+гіроскоп",
 ["3V3 ──► VCC   GND ─── GND", "SCL/SDA ──► GPIO22/21 + pull-up",
  "AD0→GND = 0x68, AD0→VCC = 0x69", "INT ──► GPIO (пробудження)",
  "Жироскоп дрейфує — потрібен фильтр"]),
"hcsr04-divider.png": ("HC-SR04 — Echo 5V через дільник!",
 ["5V ──► VCC   GND ─── GND", "GPIO5 ──► Trig (10мкс імпульс)",
  "Echo (5V!) ──► дільник 1к/2к ──► GPIO18", "distance = t_мкс / 58 (см)",
  "PIR: VCC/GND/OUT→GPIO, 5–7м"]),
"ina219-hx711.png": ("INA219 струм + HX711 ваги",
 ["INA219: VIN+/VIN− в розрив +провода, I2C", "HX711: DT→GPIO, SCK→GPIO",
  "Тензодатчик E+/E−/A+/A−, калібрування вагою", "BH1750: I2C люксометр 0x23"]),
"oled-ssd1306-i2c.png": ("OLED SSD1306 128×64 — I2C",
 ["3V3 ──► VCC   GND ─── GND", "SCL→GPIO22  SDA→GPIO21 (0x3C)",
  "U8g2 / Adafruit_SSD1306", "Яскравість нижче — довше живе"]),
"tft-st7789-spi.png": ("TFT ST7789 240×240 — SPI",
 ["3V3 ──► VCC   GND ─── GND", "SCL→GPIO18 SDA→GPIO23 (MOSI)",
  "RES→GPIO  DC→GPIO  CS→GPIO5  BLK→3V3/PWM", "TFT_eSPI: налаштувати User_Setup",
  "E-paper: BUSY довге оновлення"]),
"neopixel-5v.png": ("NeoPixel WS2812 — 5V + RMT",
 ["5V 60мА/LED ──► 5V стрічки (окремий БЖ!)", "GND спільна + конд. 1000мкФ",
  "GPIO ──► DATA через 330 Ом", "3.3V→5V: 74AHCT125 для довгих ліній",
  "Серво SG90: 50Гц, VCC 5V окремо"]),
"l298n-tb6612.png": ("L298N vs TB6612 + A4988",
 ["L298N: втрата 2V + радіатор, VM 5–35V", "TB6612: MOSFET, ККД високий",
  "A4988: Vref = I×8×Rs, MS1-3 мікрокрок", "NEMA17: VM 12–24V, sleep при простої"]),
"buck-mp1584-trim.png": ("Buck MP1584/LM2596 — порядок!",
 ["1. Без навантаження виставити Vout!", "2. Мультиметр на вихід, крутити trim",
  "3. Вимкнути, підключити ESP32", "MP1584: до 3A   LM2596: до 3A + гріється",
  "MT3608 boost: з 18650 → 5V"]),
"txs0108-i2c.png": ("TXS0108 level-shifter",
 ["VCCA=3.3V  VCCB=5V  OE→VCCA", "A-сторона → ESP32, B-сторона → 5V модуль",
  "I2C: pull-up з ОБОХ сторін", "Дільник 1к/2к — для повільних ліній"]),
"aht10-scheme.png": ("AHT10/AHT20/SHT40 — вологість I2C",
 ["3V3 ──► VCC   GND ─── GND", "SCL/SDA → 22/21 (0x38 / 0x44)",
  "AHT: калібрувальна команда при старті", "SHT40: точність ±1.8%"]),
"air-quality-scheme.png": ("BME680/CCS811/MH-Z19/PMS5003",
 ["BME680: I2C VOC+тиск", "CCS811: прогрів 48г! eCO2",
  "MH-Z19B: UART CO2, ABC-калібрування", "PMS5003: UART + вентилятор, 5V"]),
"expander-scheme.png": ("ADS1115/MCP3008/PCF8574",
 ["ADS1115: 16біт I2C PGA, ADDR", "MCP3008: SPI 10біт, 8 каналів",
  "PCF8574: 8 GPIO I2C 0x20–0x27", "MCP23017: 16 GPIO + INT"]),
"light-tof-scheme.png": ("VL53L0X/TCS34725/TSL2561",
 ["VL53L0X: ToF лазер, XSHUT для адрес", "TCS34725: RGB + clear, INT",
  "TSL2561: люкси 0x29/0x39", "Уникати прямого сонця на ToF"]),
"temp-analog-scheme.png": ("NTC/PT100/MAX6675/LM35",
 ["NTC 10к + 10к дільник → ADC (Steinhart-Hart)", "PT100 → MAX31865 SPI",
  "K-термопара → MAX6675 SPI", "LM35: 10мВ/°C → ADC1 (не ADC2+WiFi!)"]),
"mq-gas-flame-sound-scheme.png": ("MQ-гази/полум'я/звук",
 ["MQ: нагрів 150мА, прогрів 24–48г!", "AO→ADC + DO→GPIO (поріг)",
  "Полум'я KY-026: чутливий до сонця", "KY-038: MIC + регулювання"]),
"security-flow-scheme.png": ("RCWL-0516/геркон/YF-S201/pH",
 ["RCWL: OUT 3.3V, VIN 4–28V, крізь стіни!", "YF-S201: імпульси ~450/л → PCNT",
  "pH-4502C: калібрування буферами", "TDS: залежність від температури"]),
"rtc-hmi-scheme.png": ("DS3231/енкодер/клавіатура",
 ["DS3231: I2C + CR2032, SQW/INT", "KY-040: CLK/DT + SW, переривання",
  "4×4: рядки→OUT, стовпці→IN_PULLUP", "Джойстик: VRX/VRY→ADC + SW"]),
"current-magnet-force-scheme.png": ("ACS712/ZMPT/PZEM/AS5600/FSR",
 ["ACS712: offset VCC/2, мВ/А за версією", "ZMPT101B: 220V! калібрування trim",
  "PZEM-004T: UART Modbus", "AS5600: магніт над чипом, I2C"]),
"orientation-id-scheme.png": ("QMC5883/BNO055/IR/GM65",
 ["QMC5883: компас, hard-iron калібрування", "BNO055: 9-DOF + fusion",
  "VS1838: 38кГц → RMT", "GM65: UART сканер кодів"]),
"max7219-tm1637-74hc595-scheme.png": ("MAX7219/TM1637/74HC595",
 ["MAX7219: DIN→MOSI CLK→SCK CS→GPIO, каскад", "TM1637: CLK/DIO, 5V живлення",
  "74HC595: DS/SHCP/STCP, OE→GND MR→VCC", "Конд. 10мкФ біля MAX7219"]),
"pca9685-mg996r-stepper-scheme.png": ("PCA9685/MG996R/28BYJ/TMC2209",
 ["PCA9685: VCC 3.3V + V+ 5–6V серво", "MG996R: пік 2.5A — окремий БЖ!",
  "28BYJ+ULN2003: IN1–4 послідовність", "TMC2209: UART + Vref + DIAG"]),
"bts7960-ssr-solenoid-scheme.png": ("BTS7960/L9110/SSR/соленоїд",
 ["BTS7960: RPWM/LPWM + EN, VM 6–27V", "L9110S: 2 канали 800мА",
  "SSR: DC 3.3V керує AC (нуль-перехід)", "Соленоїд: MOSFET + 1N4007!"]),
"dfplayer-max98357-nextion-lcd-scheme.png": ("DFPlayer/MAX98357/Nextion/2004",
 ["DFPlayer: RX через 1к, BUSY→GPIO, microSD", "MAX98357: BCLK/LRCK/DIN I2S",
  "Nextion: 5V, UART перехресно", "2004+PCF8574: 0x27/0x3F, контраст"]),
"led-strip-power-shifter-scheme.png": ("Стрічки: живлення+рівні",
 ["60мА/LED: 300 LED = 18A пік!", "Інжекція 5V кожні 2–3м", "1000мкФ + 330 Ом на DATA",
  "74AHCT125: 3.3V→5V для довгих ліній"]),
"nfc-rfid-biometry-scheme.png": ("PN532/RDM6300/R307/GM65",
 ["PN532: SEL0/SEL1 режим, IRQ/RST", "RDM6300: 5V + TX 9600 + котушка",
  "R307: UART відбитки, TOUCH", "GM65: UART, TRIG"]),
"bt-subghz-scheme.png": ("HC-05/HM-10/CC1101/HC-12",
 ["HC-05: EN для AT, RX через дільник!", "HM-10: 3.3V BLE", "CC1101: SPI + GDO0",
  "HC-12: SET для AT, антена 433МГц"]),
"lte-eth-can-scheme.png": ("SIM7600/W5500/MCP2515",
 ["SIM7600: VBAT 3.8V 3A! + PWRKEY", "W5500: SPI + RST/INT, 3.3V",
  "MCP2515: 8МГц кварц + J1 120 Ом"]),
"radar-uwb-ir-voice-scheme.png": ("LD2410/UWB/IR/голос",
 ["LD2410: OUT + UART 256000, гейти", "DWM1000: SPI + TWR", "VS1838: OUT → RMT",
  "SU-03T: UART голосові команди"]),
"tp4056-ip5306-bms-ups-scheme.png": ("TP4056/BMS/UPS",
 ["TP4056: PROG 1.2к=1A, LED R/G", "OUT відключається при 2.4V (DW01)",
  "BMS: B+/B−/P+/P−, балансування", "UPS: MOSFET+Schottky без ресету"]),
"ldo-buck-xl4015-protect-scheme.png": ("LDO/buck/захист",
 ["AMS1117: 1A, dropout 1.1V, гріється", "ME6211: 500мА для ESP32",
  "XL4015: CC/CV, V без навантаження!", "PTC + TVS + MOSFET від переполюсовки"]),
"usb-uart-autoreset-scheme.png": ("USB-UART + auto-reset",
 ["CH340/CP2102: TX/RX перехресно", "DTR→EN + RTS→BOOT (2×NPN + 100нФ)",
  "460800 робоча, 115200 для довгих кабелів", "S2/S3: вбудований USB"]),
"hc05-scheme.png": ("HC-05 детально", ["Див. bt-subghz-scheme", "EN=HIGH → AT 38400",
  "RXD через дільник 1к/2к", "STATE → GPIO"]),
"hm10-scheme.png": ("HM-10 BLE детально", ["Див. bt-subghz-scheme", "3.3V VCC",
  "BRK для розриву", "AT+ROLE0/1"]),
"pn532-scheme.png": ("PN532 детально", ["Див. nfc-rfid-biometry-scheme",
  "I2C 0x24 / SPI / HSU", "SEL0/SEL1 перемички"]),
"rdm6300-scheme.png": ("RDM6300 125кГц", ["5V VCC, TX 9600", "Зовнішня котушка",
  "Тільки читання EM4100"]),
"sim7600-scheme.png": ("SIM7600 4G детально", ["Див. lte-eth-can-scheme",
  "PWRKEY 1с імпульс", "AT+CMQTT"]),
"w5500-scheme.png": ("W5500 Ethernet SPI", ["Див. lte-eth-can-scheme",
  "SPI 33МГц макс", "Ethernet.h бібліотека"]),
"ld2410-scheme.png": ("LD2410 радар детально", ["Див. radar-uwb-ir-voice-scheme",
  "Гейти 0–8 чутливість", "BT-конфіг HLKRadarTool"]),
"devkit-usb-power.png": ("DevKit живлення від USB",
 ["USB 5V ──► VIN ──► LDO ──► 3.3V", "GND спільна", "TX0/RX0 ──► USB-UART",
  "EN+BOOT для download-режиму"]),
"brownout-scope.png": ("Brownout при WiFi TX",
 ["Пік 500мА при TX → просадка", "Слабкий LDO/тонкі дроти = 2.9V",
  "Ліки: 470мкФ + короткий USB + 5V/2A", "Brownout detector → reboot"]),
"mqtt-broker-lwt-scheme.png": ("MQTT: вузли → брокер → підписники",
 ["ESP32 ──► PUBLISH device/<id>/sensors (QoS 0, без retain)",
  "Брокер Mosquitto :1883 plain / :8883 TLS", "LWT status=offline (retained, QoS 1)",
  "SUB device/# ──► Node-RED / дашборд", "Keepalive 30с + backoff 1/2/4/8с",
  "Паролі + ACL, анонімів з мережі — нема", "Телеметрія — без retain!"]),
"http-websocket-rest-scheme.png": ("HTTP REST + WebSocket дуплекс",
 ["POST /api/sensors JSON ──► 200 OK", "HTTPS тільки з CA-bundle + NTP-час",
  "SSE /events ──► штовхає телеметрію в браузер", "WS /ws ◄──► дуплекс команди",
  "Важкі запити — в окрему задачу (WDT!)", "urequests: кожну відповідь close()",
  "RAM TLS ~40КБ: дві сесії на C3 — межа"]),
"mdns-ntp-tls-scheme.png": ("mDNS + NTP + TLS ланцюжок",
 ["mDNS esp32.local ──► тільки одна підмережа!", "_http._tcp:80 + _mqtt._tcp:1883",
  "SNTP UDP 123 ──► UTC + TZ Київ", "Без NTP час 1970 → БУДЬ-ЯКИЙ TLS падає",
  "CA-bundle / вшитий PEM / LittleFS ca.pem", "Fingerprint — тимчасово, ламається",
  "setInsecure — тільки стенд, не прод"]),
"provisioning-blufi-rainmaker-scheme.png": ("Provisioning: портал → STA",
 ["AP ESP32-Setup + пароль + таймаут 180с", "Captive-портал 192.168.4.1: SSID+пасс",
  "BLE protocomm security1 (PoP з наліпки)", "Зберегти NVS → стоп AP → reboot → STA",
  "3 невдачі → назад у портал (не цикл!)", "Кнопка 10с → erase NVS → портал",
  "SmartConfig/BluFi — тільки legacy!"]),
"cloud-pipeline-nodered-scheme.png": ("Пайплайн: MQTT → Node-RED → InfluxDB → Grafana",
 ["Вузол wake → BME280 → PUBLISH → sleep 60с", "Mosquitto :1883 ──► mqtt-in device/#",
  "Node-RED function: нормалізація + timestamp", "InfluxDB bucket iot, retention 365d",
  "Grafana: Time series + алерт t>30", "Офлайн-буфер 50 точок, злив пачкою",
  "Без NTP — точки з міткою 1970!"]),

"gas-co2-precision-scheme.png": ("Газ/CO2 прецизійні — прогрів!",
 ["SGP30: VOC/eCO2, baseline кожні 24г", "SCD30/40: NDIR CO2, ABC-калібрування",
  "SEN5x: PM+VOC+NOx+RH/T все-в-одному", "BME688: газ + AI Heater",
  "SHT85: еталон вологості", "I2C 3.3V, прогрів 12–48г!"]),
"light-spectral-gesture-scheme.png": ("Світло/спектр/жести",
 ["TSL2591: люкси, два діоди", "AS7341: 11 каналів спектру",
  "VL53L1X: ToF до 4м, ROI", "APDS9960: жести + наближення",
  "I2C 3.3V + pull-up", "Уникати прямого сонця на ToF"]),
"imu-6-9dof-scheme.png": ("IMU 6/9-DOF",
 ["ADXL345: free-fall переривання", "LSM6DSx: FIFO + Machine Core",
  "ICM-20948: DMP 9-DOF", "BNO08x: вбудований fusion + RVC UART",
  "Компас: hard/soft-iron калібрування", "Вібрації кріплення — фільтр"]),
"bio-ir-temp-scheme.png": ("MAX30102 + MLX90614",
 ["MAX30102: червоний+ІЧ LED, притисни палець", "SpO2: відношення R/IR",
  "MLX90614: безконтактно, кут FOV!", "Емісивність шкіри ~0.98",
  "I2C 3.3V", "Рух = артефакти пульсу"]),
"energy-meters-scheme.png": ("Лічильники енергії — 220V!",
 ["INA226: 16біт + alert", "HLW/CSE: НЕІЗОЛЬОВАНА мережа!",
  "SDM120: Modbus RTU", "MCP3421: точний АЦП шунта",
  "!!! Тільки через ізольований БЖ/трансформатор !!!", "Запобіжник обов'язковий"]),
"displays-2-tft-smart-scheme.png": ("ST7735/SH1106/смарт-дисплеї",
 ["ST7735: SPI + TFT_eSPI", "SH1106: сторінкова адресація (не SSD1306!)",
  "TM1638: кнопки+LED+7seg", "DWIN/TJC: UART HMI-редактор",
  "3.3V логіка, 5V підсвітці — окремо", "Буфер кадру в PSRAM"]),
"powermotion-bldc-foc-scheme.png": ("DRV/TB6600/FOC",
 ["DRV8825: M0-M2 + Vref", "TB6600: дипи струму, 24-48V!",
  "TMC5160: SPI + StallGuard", "FOC: 3-фазний міст + енкодер",
  "L298N для BLDC НЕ годиться", "Спільний GND + 1000мкФ"]),
"cellular-nbiot-uartlora-scheme.png": ("SIM7080/A7670/LoRa-UART",
 ["SIM7080: Cat-M/NB-IoT, 4V 3A!", "A7670: 4G-наступник SIM800",
  "E32/E22: M0/M1 режими, AT+ADDRESS", "SX1262: TCXO, +22дБм",
  "Антени LTE і LoRa РІЗНІ!", "PWRKEY імпульс 1с"]),
"esp32-c2-p4-scheme.png": ("ESP32-C2 / P4 / ESP8684",
 ["C2: дешевий вузол WiFi4+BLE5", "P4: БЕЗ радіо! хост камер/дисплеїв",
  "P4 + C6 = радіо-компаньйон", "ESP8684: SiP з flash",
  "C3 — золота середина", "P4: MIPI/USB, потрібен PHY"]),
"cookbook-weather-scheme.png": ("Метеостанція: BME280+SHT40 + solar",
 ["BME280 0x76 + SHT40 0x44 ──► I2C 21/22", "Deep-sleep 600с ──► MQTT sensors",
  "TP4056 + 18650 + панель 5V 1A", "VBAT ──► дільник 100к/100к ──► GPIO34",
  "Корпус IP65 + жалюзі-екран", "JSON ──► Node-RED ──► Grafana"]),
"cookbook-tracker-scheme.png": ("GPS-трекер: NEO-M8N + A7670",
 ["NEO-M8N TX/RX ──► GPIO16/17 (UART2)", "A7670 TX/RX ──► GPIO26/27 (UART1)",
  "LM2596 3.8V + 1000мкФ (пік 3A!)", "PWRKEY ──► GPIO25 імпульс 1с",
  "MPU6050 INT ──► GPIO33 wake по руху", "MQTT track ──► geofence в Node-RED"]),
"cookbook-access-scheme.png": ("СКУД: RC522 + реле + MQTT + OTA",
 ["RC522 3.3V! ──► SPI 18/19/23 + SS 5 RST 22", "Реле GPIO27 ──► замок 12V + 1N4007",
  "Кнопка виходу ──► GPIO34 + зуммер 25", "allow/deny списки ──► NVS",
  "access/event QoS1 ──► журнал", "OTA по access/fw з rollback"]),
"cookbook-energy-scheme.png": ("Енергомонітор: PZEM-004T + MQTT",
 ["PZEM L/N ──► мережа через запобіжник 1A!", "CT на ОДНУ фазу, стрілка до навантаження",
  "PZEM TX(5V) ──► дільник ──► GPIO16", "GPIO17 ──► PZEM RX",
  "!!! 220V: тільки знеструмленим, DIN-бокс !!!", "MQTT 10с ──► InfluxDB ──► Grafana"]),

"firmwares-wled-tasmota-scheme.png": ("Готові прошивки: WLED/Tasmota/Blynk",
 ["WLED: сегменти/ефекти/пресети, sync UDP", "Tasmota: tele/stat/cmnd + Rules",
  "Blynk: токен + віртуальні піни V0..", "Homie: homie/5/.../$state",
  "Своя прошивка — коли логіка складна", "Струм стрічок рахуй завжди!"]),
"notify-voice-telegram-scheme.png": ("Сповіщення і голос",
 ["Telegram-бот: токен + whitelist чатів", "CallMeBot: WhatsApp без свого бота",
  "IFTTT/Pushover: Webhooks + priority", "fauxmoESP: Alexa Hue-емуляція",
  "Long-poll + deep-sleep несумісні!", "Фото з камери в повідомленні"]),
"security-hardening-scheme.png": ("Ланцюг довіри і чек-лист",
 ["Boot ROM → Secure Boot → підписана app", "Flash Encryption + anti-rollback",
  "JTAG lock / download-disable = необоротно!", "NVS-шифрування секретів",
  "OTA тільки HTTPS з підписом", "Унікальні паролі з mfg-партиції"]),
"usb-host-msc-hid-scheme.png": ("USB-host S2/S3: MSC/HID",
 ["TinyUSB host: MSC флешка FAT", "HID: клавіатура/миша-репорти",
  "CDC-хост до Arduino/модема", "VBUS 5V/500мА + OTG-кабель",
  "Пасивні хаби часто не працюють", "Serial-JTAG для дебагу"]),

"gas-2-voc-industrial-scheme.png": ("Гази-2: VOC/промислові",
 ["ENS160: індекс AQI", "SGP40/41: VOC + NOx",
  "TGS/MQ: Rs/R0, прогрів!", "ZE08: UART, калібрований ppm",
  "Електрохімічні — не для хобі", "Нагрівачі: 150мА+"]),
"dust-co2-2-scheme.png": ("Пил і CO2-2",
 ["SPS30: автоочищення вентилятора", "PMS/SDS: дешевий пил, дрейф",
  "K30/SCD41: NDIR/фотоакустика", "MH-Z: дивись діапазон!",
  "ABC-калібрування на вулиці", "UART 9600/115200"]),
"pressure-level-scheme.png": ("Тиск/глибина/рівень/потік",
 ["MS5611: альтиметр 10см", "MS5837: глибина, гель!",
  "MPXV7002: трубка Піто", "SFM3000: масовий потік",
  "XKC-Y25: крізь стінку бака", "Герметизація роз'ємів!"]),
"mag-imu-2-scheme.png": ("Магніт/холл/IMU-2",
 ["MMC5983: компас 0.4мГа", "TLV493D: 3D-холл",
  "A3144: магнітні двері", "BMI270/BMA400: кроки/сон",
  "Калібрування біля моторів!", "I2C + INT-пін"]),
"light-uv-irarray-scheme.png": ("УФ/тепловізор/ToF/лідар",
 ["VEML6075: УФ-індекс", "AMG8833/MLX90640: тепловізор",
  "VL53L5CX: 8x8 зон", "TF-Luna: лідар UART",
  "RPLIDAR: SLAM оглядово", "JSN-SR04T: волога!"]),
"time-mem-io-scheme.png": ("RTC/FRAM/IO/ЦАП/АЦП",
 ["PCF8523: ppm точність", "FRAM: мільярди циклів",
  "TCA9548: 8 каналів I2C", "MCP4725: ЦАП 12біт",
  "ADS1256: 24-біт АЦП", "NVS для лічильників — знос!"]),
"industrial-fieldbus-scheme.png": ("Промисловість: шини і 220V",
 ["CANopen: SDO/PDO", "DMX: 250кбод сцена",
  "4-20мА: XTR115 + шунт", "TRIAC: zero-cross + ІЗОЛЯЦІЯ",
  "!!! 220V: DIN-бокс, запобіжник !!!", "Ізольований RS485 для цеху"]),
"lab-instruments-scheme.png": ("Прилади: міряй правильно",
 ["Струм сну — через розрив джампера", "VIN при TX — осцилограф ×10",
  "I2C/SPI — логіка + PulseView", "Перше ввімкнення — CC-ліміт!",
  "USB-тестер ловить charge-only", "Burden voltage на мА!"]),
"breadboard-limits-scheme.png": ("Макетка: межі і правила",
 ["Стрепінг-піни не чіпати при boot!", "USB-кабель з даними, не зарядка!",
  "WiFi-TX садить живлення — bulk!", "I2C коротко, SPI до 1 МГц",
  "EN-кнопка замість висмикування", "Далі — паяна плата!"]),
"soldering-connectors-scheme.png": ("Пайка і конектори",
 ["320–370°C + флюс-гель", "Кримп SN-28B + pull-test",
  "JST крок: XH 2.5 / PH 2.0 / GH 1.25", "WAGO 221 замість скруток",
  "Dupont глючить — пропаяй!", "Силіконові дроти, AWG за струмом"]),
"enclosure-cert-factory-scheme.png": ("Корпус/сертифікат/завод",
 ["IP65 + вводи + конденсат!", "Conformal від вологи",
  "CE/FCC: модульна сертифікація", "mfg-NVS: серійники і паролі",
  "Self-test при першому boot", "Фейк DS18B20/CH340 — тести!"]),
"freertos-patterns-scheme.png": ("FreeRTOS-патерни",
 ["WiFi живе на ядрі 0", "Черги, не глобалки!",
  "IDLE не голодувати", "ISR: IRAM, без printf",
  "Mutex проти інверсії", "Автомат станів WiFi-MQTT"]),
"testing-ci-scheme.png": ("Тести і CI",
 ["Unity test-компонент", "Actions: build+tests матриця",
  "HIL: друга плата тестер", "Semver + stable/beta OTA",
  "Golden-файли драйверів", "ESP_LOG рівні"]),
"tooling-deep-scheme.png": ("IDF/PIO/MP вглиб",
 ["idf_component.yml + Manager", "sdkconfig.defaults",
  "PIO envs + extra_scripts", "Frozen-модулі + mpy-cross",
  "ulab замість numpy", "uasyncio-сервер"]),
"tinyml-voice-scheme.png": ("TinyML і голос",
 ["Edge Impulse: дані→імпульс→деплой", "TFLM: арена в PSRAM!",
  "ESP-SR: wake word офлайн", "ESP-WHO: обличчя на камері",
  "int8-квантування", "Шум вбиває точність"]),
"pid-filters-scheme.png": ("ПІД і фільтри",
 ["P/I/D + anti-windup", "Hotend: NTC + MOSFET + PID",
  "Complementary vs Kalman", "Медіана проти викидів",
  "Дебаунс: таймер, не delay", "Гістерезис термостата"]),
"matter-thread-zigbee-scheme.png": ("Matter/Thread/Zigbee",
 ["Matter: BLE+QR комісіонування", "Clusters/endpoints/fabric",
  "Thread: C6/H2 радіо + BR", "Zigbee: ZHA/Z2M pairing",
  "Matter vs Zigbee vs BLE", "OTA через Matter"]),
"ble-mesh-a2dp-hid-scheme.png": ("BLE-Mesh/A2DP/HID",
 ["Mesh: provisioning + моделі", "Publish/subscribe груп",
  "A2DP-sink на I2S-ЦАП", "HID-клавіатура",
  "ANCS з iPhone", "Групи замість пар!"]),
"audio-codecs-es8388-scheme.png": ("Аудіокодеки I2S",
 ["ES8388: I2C 0x10 + I2S", "PCM5102: без MCLK!",
  "MCLK/BCLK/LRCK/DIN", "AudioKit/LyraT готові",
  "WAV з SD по DMA", "Навушники + мік"]),
"rc-protocols-sbus-mavlink-scheme.png": ("RC-протоколи",
 ["SBUS: 100к 8E2 + інвертор!", "CRSF/ELRS: 420к + телеметрія",
  "MAVLink: heartbeat + CRC-extra", "DShot через RMT, не PWM!",
  "QGroundControl для тестів", "Failsafe налаштуй!"]),
"camera-streaming-mjpeg-scheme.png": ("Камера: стрим і коди",
 ["MJPEG /stream + fb×2 в PSRAM", "QVGA для розпізнавання",
  "QR/AprilTag тільки GRAYSCALE", "Timelapse на SD",
  "Фото в Telegram", "Світло + фокус!"]),
"lvgl-squareline-scheme.png": ("LVGL + SquareLine",
 ["flush_cb + tick 5мс", "Буфери SRAM/PSRAM",
  "SquareLine: логіка поза ui/", "arc/bar/chart/keyboard",
  "Кирилиця через конвертер", "FPS рахуй від SPI"]),

"env-newgen-scheme.png": ("Нові кліматичні сенсори",
 ["BMP585: шумовий поріг 0.08 Па", "BME690: AI-класифікація BSEC2", "SEN66: 6 параметрів в одному", "AHT21: покращений стабільність", "ENS161: 4 елементи, прогрів 3 хв"]),
"imu-mag-3-scheme.png": ("Інертна навігація та магнітометри",
 ["BMI088: окремі кринали Acc/Gyro", "BMI160: вбудований шагомір", "ADXL355: сейсмічна точність", "ADXL375: вимірювання ударів", "MMC5603: 16-біт, RM3100: 20 нТл"]),
"light-color-2-scheme.png": ("Світло/Колір/спектр",
 ["AS7262/AS7265x: 6/18 каналів", "VEML6040: RGBW", "OPT4001: автоomotive", "TMD3725: колір+близнаDist", "SI1133: УФ+ALS", "LTR-390UV: УФ-дешево"]),
"range-lidar-60ghz-scheme.png": ("Далекоміри та 60 ГГц радари",
["VL53L4CD: 1.3 м", "VL53L7CX: 8×8 матриця", "TMF8821: SPAD-direct ToF", "LD19/YDLIDAR: 360° UART", "BGT60TR13C: 60 ГГц FMCW", "MR24HPC1: присутність+дихання"]),
"temp-precision-scheme.png": ("Прецизійна температура та термопари",
 ["MAX31856: SPI універсальний", "MCP9600: I2C cold-junction", "MAX31855: термопара K", "PT1000: 2/3/4-провідне", "STS35/ADT7410: ±0.1 °C", "MAX30208: медичний"]),
"displays-3-oled-tft-eve-scheme.png": ("Дисплеї 3: SSD1322/SSD1351/ST7796/GC9A01/RA8875/FT81x",
["SSD1322: 128×128 сірий", "SSD1351: 128×128 Colour", "ST7796: 480×320 TFT", "GC9A01: 240×240 Kreis", "RA8875: 3.5 TFT", "FT81x: GPU Elektor"]),
"input-io-2-scheme.png": ("Елементи вводу/виводу",
 ["TTP223: вільний GPIO", "TTP229: 16-канальна SPI", "MPR121: 12 ємнісних I2C", "CAP1188: 8 ємнісних+LED", "AS5048A: 14-біт SPI", "MT6701/TLE5012: кут SPI", "AMT22: 12-біт SPI", "SX1509: 16 GPIO I2C", "IS31FL3731: I2C LED", "HT1621: 3-wire SPI", "ADNS-5050: SPI 2-wire", "PMW3360: SPI 4-wire"]),
"eink-controllers-scheme.png": ("E-Ink: контролери і сон",
 ["SSD1680/UC8151: SPI + BUSY!", "Partial 0.3с vs full 2с",
  "3 кольори: ч/б/червоний", "Живлення різати в сні!",
  "GxEPD2 + Waveshare HAT", "Гостінг лікуй full-refresh"]),
"lcd-char-hd44780-scheme.png": ("HD44780: символи і шина",
 ["4-біт режим, RS/RW/E", "CGRAM: свої гліфи/кирилиця",
  "2004: DDRAM рядки!", "PCF8574: 0x27/0x3F сканер",
  "Vo контраст + PWM підсвітки", "I2C pull-up 4.7к"]),
"touchscreens-cap-res-scheme.png": ("Тачскріни cap/res",
 ["CST816/GT911: I2C + INT/RST", "XPT2046: SPI + тиск Z",
  "Калібрування 3 точки", "LVGL indev прив'язка",
  "Мультитач тільки cap", "Шлейф не перегинай!"]),
"buttons-switches-pots-scheme.png": ("Кнопки/тумблери/поти",
 ["NO/NC + SPST/SPDT", "E-Stop тільки NC-ланцюг!",
  "Pull-up: 10к/4.7к/45к", "Дебаунс: RC/Schmitt/SW",
  "4x4 скануванням", "X9C103 цифровий пот"]),
"proximity-industrial-inputs-scheme.png": ("Промвходи 12/24V",
 ["LJ12A3: метал 4мм", "E18-D80NK дифузний",
  "NPN vs PNP схеми", "PC817: R за струмом!",
  "Сухий контакт", "Спільний GND!"]),
"rfid-advanced-mifare-scheme.png": ("RFID вглиб: Mifare/UHF",
 ["Trailer: KeyA/Access/KeyB", "Value-блоки: +/-/transfer",
  "T5577: перезаписуваний 125кГц", "UHF: 30дБм + антена!",
  "Wiegand 26/34-bit", "Classic зламаний (Crypto-1)"]),
"ble-gateway-tracker-scheme.png": ("BLE-шлюз і трекер",
 ["Active vs passive scan", "ESPresense: кімната!",
  "pvvx ATC + bindkey", "d=10^((Tx-RSSI)/10n)",
  "MQTTDiscovery в HA", "Фільтр дублікатів!"]),
"ble5-longrange-audio-scheme.png": ("BLE5: дальність і аудіо",
 ["Coded S2/S8: км!", "2M + DLE + MTU-517",
  "AoA/CS: ESP32 НЕ вміє", "LE Audio: LC3/BIS",
  "PAwR для цінників", "Чесна таблиця в ноті"]),
"i2s-deep-tdm-pdm-scheme.png": ("I2S вглиб: DMA/TDM/PDM",
 ["BCLK=SR×слоти×біти", "APLL для 44.1кГц!",
  "DMA-буфер vs клацання", "PDM тільки S3!",
  "Full-duplex echo-камера", "WAV-заголовок допиши!"]),
"mp3-tts-amps-scheme.png": ("MP3/TTS/підсилювачі",
 ["JQ6500: звіряй ревізію!", "SYN6288: GB2312!",
  "PAM8403 гудить від 5V", "TPA3116: 50Вт + радіатор",
  "Star-ground від петель!", "BUSY-пін обов'язково"]),
"webradio-streaming-scheme.png": ("Вебрадіо і стрим",
 ["Icecast URL + метадані", "helix-MP3/AAC в PSRAM",
  "Кільце-буфер vs заїкання", "SqueezeLite/Snapcast",
  "VS1053: апаратний декод", "MP сам не тягне!"]),
"offline-voice-uart-scheme.png": ("Офлайн-голос по UART",
 ["LD3320: список IDX", "CI-03T: кадри AA 55",
  "UNI3588: CRC16!", "15 vs 50 vs 100+ слів",
  "Мікрофон + шум!", "Реле ID 0x01-0x08"]),
"voice-assistant-pipeline-scheme.png": ("Голосовий конвеєр",
 ["mWW на ESP32!", "Assist→Wyoming→Piper",
  "Порти 10200/10300/10400", "Opus не влізає!",
  "Atom Echo без PSRAM", "Все локально!"]),
"devboard-mini-s2s3-scheme.png": ("Міні-плати S2/S3",
 ["QT Py: STEMMA!", "TinyS3: LiPo+gauge",
  "Lolin mini: дешево", "Nano ESP32: NORA!",
  "Пінів мало — плануй!", "USB-C всюди"]),
"devboard-hmi-guition-scheme.png": ("HMI-плати S3",
 ["Guition JC8048: дешево!", "Живлення дисплея окремо",
  "LVGL/SquareLine", "WT32-SC01: 2×LDO",
  "T-Embed: dial+encoder", "RGB-таймінги!"]),
"devboard-retro-wearable-scheme.png": ("Ретро і носиме",
 ["VGA32: тільки classic!", "Odroid-GO: геймпад",
  "T-Watch: годинник", "T-Deck: Meshtastic!",
  "Батарея + сон", "Клавіатура по SPI"]),
"esp32-c5-c61-scheme.png": ("ESP32-C5 / C61",
 ["C5: WiFi6 dual-band!", "C61: дешевший C6",
  "IDF 5.5+/Arduino 3.3+", "Прикладів поки мало!",
  "C6 vs C5 vs C61 таблиця", "Міграція з C3"]),
"gnss-rtk-zedf9p-scheme.png": ("GNSS-RTK: сантиметри!",
 ["ZED-F9P: база+ровер", "NTRIP-клієнт на ESP32",
  "Антема + ground plane!", "UBX vs NMEA vs RTCM3",
  "LC29H: дводіапазонний", "RTKLIB/u-center"]),
"cellular-lora-2-scheme.png": ("Cat-1 і LoRa-2",
 ["EC200U: заміна 2G!", "E78/RAK3172: nRF+LoRa",
  "SX1280: 2.4ГГц!", "LR1121: +супутник",
  "Антени LTE vs LoRa", "AT: CSQ/CEREG"]),
"wired-2-eth-can-tools-scheme.png": ("Дротові-2 і CAN-тулз",
 ["Modbus TCP шлюз :502", "ENC28J60 для C3!",
  "CANable: SLCAN-міст", "ISO1050 + B0505S!",
  "Wireshark can.id", "Alt PHY strap!"]),
"nfc-biometry-2-scheme.png": ("NFC-2 і біометрія",
 ["PN5180: потужний!", "DESFire: AES-файли",
  "NTAG: спочатку PWD!", "GT-521F32 протокол",
  "DE2120 vs GM65", "Читач→задача"]),
"motion-control-fluidnc-scheme.png": ("Рух: ЧПК/дрони/ROS",
 ["FluidNC: config.yaml!", "grbl $налаштування",
  "Klipper: ESP32 slave", "micro-ROS агент!",
  "ESP-Drone позиція", "CRSF-телеметрія!"]),
"automotive-obd-lin-scheme.png": ("Авто: OBD/LIN/TPMS",
 ["ELM327 AT-команди", "010C RPM формула!",
  "LIN: break+checksum", "TPMS білий список",
  "Load dump 40V+!", "KeeLoq тільки свої"]),
"marine-time-nmea-scheme.png": ("Море і точний час",
 ["NMEA2000: 250кбіт!", "PGN-таблиця",
  "DCF77: 100/200мс", "GPSDO holdover",
  "IP67 + Gore!", "12/24V ізоляція"]),
"pcb-design-ground-scheme.png": ("Своя плата: земля і фільтри",
 ["Plane цілий, різати — ні!", "Star для аналога",
  "100нФ біля кожного VCC", "Ферит+pi від RF",
  "Keepout + CLC!", "TVS на роз'єми"]),
"sensor-tails-scheme.png": ("Хвости сенсорів",
 ["DPS368: IPx8!", "LPS28: 30м глибина",
  "BMP384: гель", "TSOP: несуча 36-56кГц",
  "TSL2581: НЕ брати!", "Chip-ID перевірка"]),
"diagnostic-map-scheme.png": ("Карта діагностики: симптом→прилад→сигнал",
 ["Лог монітора першим!", "Паніка → addr2line", "WiFi → RSSI і живлення",
  "I2C → аналізатор", "Живлення → осцилограф", "Війністорії всередині!"]),
"c6-h2-zigbee-thread-scheme.png": ("C6/H2: Zigbee vs Thread vs Matter",
 ["Zigbee: готовий mesh з коробки", "Thread: IP в кожен вузол", "Matter: поверх Thread/WiFi",
  "H2 без WiFi — тільки 15.4!", "Border Router тримає міст", "Sleepy: спить, батько буферить"]),
"nano-esp32-scheme.png": ("Nano ESP32: Arduino-форма",
 ["NORA-W106 всередині (S3)!", "USB-C + офіційне ядро", "Cloud і MicroPython з коробки",
  "Піни Nano-розкладки!"]),
"sources-sensors-scheme.png": ("Джерела: сенсори",
 ["Даташит виробника першим!", "Продукт + живе фото", "Туторіал з кодом",
  "Перевірено 200, не вгадано!"]),
"sources-modules-scheme.png": ("Джерела: модулі",
 ["Компонент → даташит → фото → код", "Espressif-доки — база", "Ревізії звіряти!",
  "Живі фото, не копії!"]),
"versions-matrix-scheme.png": ("Версії і матриця",
 ["IDF/Arduino/MP гілки", "C5/C61: свіжі версії!",
  "Чип→мін.версія", "Штамп Перевірено",
  "Оновлення щокварталу", "CHANGELOG веди!"]),
"ina3221-3ch-scheme.png": ("INA3221 — 3 канали, спільний GND!",
 ["Шунти 0.1 Ом у розрив PV+/BAT+/LOAD+", "Sense-доріжки короткі, витою парою",
  "Мінуси всіх ліній + GND ESP32 в одну точку", "Канали НЕ ізольовані!",
  "I2C + alert-піни на перевантаження"]),
"hlw8012-cf-scheme.png": ("HLW8012 — імпульси CF/CF1",
 ["CF ──► GPIO (переривання, P = k/T)", "CF1 ──► GPIO (струм/напруга за SEL)",
  "Калібрування лампою 60 Вт", "UART НЕМАЄ — тільки частота!"]),
"sct013-burden-scheme.png": ("SCT-013 — кліпса + burden!",
 ["Фаза крізь кільце (стрілка до навантаження)", "Burden 10–33 Ом ОБОВ'ЯЗКОВО",
  "Дільник/зсув на 1.65 В → ADC", "Без burden — сотні вольт!"]),
"ds3218-power-scheme.png": ("DS3218 — окремий БЖ 5 А!",
 ["БЖ 6V/5A ──► VCC, GND спільна з ESP32", "GPIO ──► SIG (PWM 50 Гц, 0.5–2.5 мс)",
  "Провід живлення ≥0.75 мм²", "USB ESP32 НЕ живить серво!"]),
"tmc2226-uart-scheme.png": ("TMC2226 — UART замість Vref",
 ["VM 4.75–29V + 100 мкФ біля драйвера", "VIO 3.3V від ESP32 ОБОВ'ЯЗКОВО",
  "STEP/DIR + UART (струм, StealthChop)", "Пін-сумісний з TMC2209"]),
"ld2410c-out-scheme.png": ("LD2410C/LD2420 — OUT як PIR",
 ["5V ──► VCC (+100мкФ)", "OUT ──► GPIO4 (HIGH = присутність)",
  "UART тільки для конфігу", "Гейти/пороги — під свою модель!"]),
"ds3231m-vbat-scheme.png": ("DS3231M — VBAT не забудь!",
 ["Без батарейки = скидання часу!", "VBAT ──► CR1220/іоністор",
  "I2C 0x68, код як у DS3231", "Точність ±5 ppm"]),
"pn7150-i2c-scheme.png": ("PN7150 — VEN + IRQ!",
 ["SDA/SCL + pull-up 4.7к", "GPIO5 ──► VEN (HIGH = робота)",
  "GPIO4 ◄── IRQ (картка в полі)", "NCI: емуляція картки + P2P"]),
"r503-uart-scheme.png": ("R503 — drop-in замість R307",
 ["UART 57600, той самий протокол!", "Шаблони НЕ переносяться — enroll заново",
  "IP65-кільце для вулиці"]),
"ws2815-12v-scheme.png": ("WS2815 — 12V + резерв Bi!",
 ["12V БЖ ──► стрічка, інжекція кожні 5 м", "GPIO ──► DIN через 74AHCT125",
  "Bi/B0 — обхід одного битого LED", "GND спільна обов'язково!"]),
"flash-psram-scheme.png": ("Flash/PSRAM — режими і розміри",
 ["DIO/QIO з даташиту мікросхеми!", "PSRAM увімкнути в menuconfig",
  "OTA — від 4 МБ", "80 МГц тільки на коротких трасах"]),
"level-shifters-scheme.png": ("Рівні 5V↔3.3V — що коли",
 ["Повільне вниз: дільник 1к/2к", "Двобічно: TXS0108 / BSS138",
  "Швидке: NT0104/SN74LVC2T45", "I2C: pull-up З ОБОХ боків"]),
"agro-soil-weather-scheme.png": ("Агро-сенсори: ґрунт NPK/7-в-1, погода",
 ["NPK/7-в-1: RS485-Modbus A/B → GPIO16/17",
  "Анемометр: імпульси → GPIO13 (PCNT)", "Флюгер: резистивний дільник → ADC",
  "Опадомір (tipping bucket): геркон → GPIO14",
  "Вологість ґрунту (ємнісний!): ADC GPIO34",
  "Atlas EZO pH/EC/DO: I2C/UART 3.3V",
  "PAR-квантовий сенсор: ADC, без тіні!",
  "Клапани поливу: 24VAC через реле + варистор"]),
"bio-2-ecg-emg-scheme.png": ("Біопотенціали: ECG/EMG",
 ["AD8232: 1-канальний ECG, LOD+/LOD−, RLD",
  "MAX30003: ECG AFE, SPI, FIFO 32, 85 мкВт",
  "MyoWare: EMG-огинаюча → ADC GPIO32/33",
  "ADS1299: 24-біт, 8 каналів ECG/EEG, SPI",
  "Електроди Ag/AgCl, RLD — середина живлення!",
  "Фільтр: 0.5–40 Гц, режектор 50 Гц",
  "Харчування від батареї, БЕЗ мережі 220V!"]),
"diy-instruments-ad9833-scheme.png": ("DIY-прилади: генератор/тестер/розширювачі",
 ["AD9833: DDS-генератор, SPI 18/23/19",
  "GM328: ESR/RLC-тестер (окремий МК!)",
  "CD74HC4067: 16-канальний мультиплексор",
  "DS2482: I2C→1-Wire міст 0x18",
  "SC16IS750: I2C→UART міст 0x48",
  "W25Q32: SPI-flash для логів/OTA",
  "Qi-приймач: 5V → buck → ESP32"]),
"secure-elements-atecc-scheme.png": ("Безпечні елементи: ATECC608/SE050",
 ["ATECC608: I2C 0x60, ECDH/ECDSA, TRNG",
  "SE050: I2C, аплети + SCP03",
  "EST: eFuse-ключі Espressif (XTS-AES)",
  "mfg-NVS: серійники через mfg_gen.py",
  "espefuse: burn-key + write-protect",
  "Secure Boot: ROM → bootloader → app",
  "NVS-шифрування: унікальний ключ на виріб"]),
"mqtt-client-3stack-scheme.png": ("MQTT-клієнт: esp-mqtt / PubSubClient / umqtt",
 ["esp-mqtt: реконект + LWT + TLS, keepalive 30с",
  "PubSubClient: тільки QoS 0, setBufferSize!",
  "umqtt.robust: блокувальний, гляди WDT",
  "Mosquitto: 1883 plain / 8883 TLS",
  "Топіки device/<id>/sensors|status|set",
  "Retain — тільки state/config, не потік!",
  "TLS ~40 КБ heap: на C3 без PSRAM — межа"]),
"sim800l-sms-call-scheme.png": ("SIM800L: SMS, дзвінки, USSD, GPRS, сон",
 ["SMS Text: CMGF=1 + CMGS + Ctrl+Z",
  "Кирилиця: PDU або UCS2-hex, або трансліт",
  "Дзвінок: ATD+380...; (з ';'!) + білий список",
  "USSD: CUSD=1 баланс; APN kyivstar/internet",
  "GPRS: CGATT → SAPBR → HTTPACTION → TERM",
  "HTTPS: HTTPSSL=1 + реальний CCLK-час!",
  "Сон: CSCLK=2, будять RI/DTR"]),
"sim-powerholder-scheme.png": ("SIM + живлення стільникових модулів",
 ["nano/eSIM; PIN ВИМКНЕНО (CLCK SC,0)",
  "DET → GPIO-переривання; TVS на DATA!",
  "VBAT 4.0V buck 3A + 1000 мкФ low-ESR",
  "Пік 2–3A слотом 577 мкс — тільки buck!",
  "Суперкап 4–10Ф через 10 Ом — костиль",
  "Шунт 0.05 Ом + скоп: пік і просадка",
  "GSM-антена ≠ GNSS-антена!"]),
"industrial-sensors-iolink-hart-scheme.png": ("Промислові сенсори: 4–20 мА / HART / IO-Link",
 ["Петля: шунт 250 Ом → 1–5V → АЦП",
  "Live zero: 4 мА = 0%, 0 мА = ОБРИВ!",
  "HART: FSK 1200/2200 поверх петлі",
  "IO-Link: C/Q 24V через трансивер",
  "XTR115: ЦАП + RC, не ШІМ!",
  "Ізоляція 24V: ISO7741 обов'язково"]),
"wireless-sensors-ble-thread-scheme.png": ("Бездротові сенсори: BLE / Zigbee / Thread",
 ["BLE-маяк pvvx → ESP32-шлюз → MQTT",
  "Zigbee: pairing кнопкою + binding!",
  "Thread SED: спить, питає parent",
  "Matter: BLE + QR-комісіонування",
  "C6/H2 для 15.4; classic — тільки BLE",
  "CR2450 ~рік: reporting з дельтою!"]),
"devboard-c6-boards-scheme.png": ("Плати C6: DevKitC / Beetle / XIAO / mini",
 ["WiFi6 + BLE5 + 802.15.4 в одному!",
  "Native USB всюди; шити через BOOT",
  "GPIO8 = RGB + strapping — не чіпати!",
  "Роутер НЕ спить — тільки мережа!",
  "C61: перевірити ядро перед партією"]),
"devboard-h2-boards-scheme.png": ("Плати H2: DevKitM / Beetle / nano",
 ["BLE5 + 802.15.4; WiFi НЕМАЄ!",
  "Тільки SED/вузли + хост з WiFi!",
  "Цегла → GPIO25 + BOOT + Reset",
  "H2 — end device, не контролер",
  "nano без charging — найекономніші"]),
"cloud-aws-iot-scheme.png": ("AWS IoT Core: сертифікати, Shadow, Jobs",
 ["X.509 трійка +ats endpoint :8883",
  "SNTP ДО connect — інакше CONNACK 5!",
  "clientID = Thing name буквально",
  "Shadow: desired чекає сплячих",
  "Jobs: OTA на парк; Fleet: claim→свій"]),
"cloud-azure-iot-scheme.png": ("Azure IoT Hub: SAS, DPS, Twins",
 ["SAS se=now+3600; регенерація завчасно!",
  "Username — цілий URL; sr lowercase!",
  "PubSubClient: setBufferSize(512)!",
  "Сплячим — Twins, живим — Methods",
  "DPS один раз → hub в NVS"]),
"mqtt-sn-gateway-scheme.png": ("MQTT-SN: UDP, topic-id, сон, шлюз",
 ["UDP + topic-id 2 байти замість рядків",
  "Predefined: реєстрація не потрібна",
  "Sleep: шлюз буферизує QoS1!",
  "Шлюз transparent vs aggregating",
  "QoS −1: publish без CONNECT"]),
"stencil-reflow-profile-scheme.png": ("Stencil + reflow: паста і профіль",
 ["Апертури 90%; QFN — windowpane!",
  "SAC305: пік 235–250°C, soak 60–120 с",
  "Паста 2 год гріється; термопара НА ПЛАТІ",
  "Tombstoning/bridging — див. таблицю",
  "Охолонення природне, руки геть!"]),
"conformal-coating-ip65-scheme.png": ("Лак + IP65 + компаунд",
 ["Акрил 2–3 тонкі шари; УФ-контроль",
  "Маскувати: BME, USB, антену, кнопки!",
  "Лак + корпус IP65 — тільки разом",
  "Компаунд: тест ДО, батареї НАЗОВНІ",
  "Gore + дренаж + силікагель"]),
"idf-setup-build-scheme.png": ("ESP-IDF: встановлення і цикл",
 ["install.sh + export.sh (кожна сесія!)",
  "idf.py set-target esp32/s3/c3/c6/h2",
  "menuconfig → sdkconfig.defaults!",
  "build → flash → monitor (однією)",
  "C6/H2 — тільки IDF 5.1+"]),
"arduino-pio-flow-scheme.png": ("Arduino + PlatformIO",
 ["Arduino: ядро ESP32 + плата + Upload",
  "PIO: platformio.ini + lib_deps!",
  "Бібліотеки: точні версії, не latest",
  "Monitor 115200; JTAG-кнопка в PIO",
  "3.x = IDF 5.x: старі скетчі мігрувати"]),
"micropython-flash-tools-scheme.png": ("MicroPython: прошивка і робота",
 ["erase_flash → firmware.bin під СВІЙ чип!",
  "Thonny / mpremote / rshell",
  "boot.py один раз → main.py цикл",
  "REPL по USB: швидкі проби",
  "frozen-модулі: своє в прошивку"]),
"esptool-flash-verify-scheme.png": ("esptool: запис і перевірка",
 ["BOOT + EN = download-режим",
  "0x0 bootloader + 0x8000 part + 0x10000 app",
  "baud 921600; не йде → 115200!",
  "verify + flash_id після запису",
  "90% бід: кабель charge-only!"]),
"jtag-openocd-gdb-scheme.png": ("JTAG: OpenOCD + GDB",
 ["TDI/TDO/TCK/TMS + GND (коротко!)",
  "Вбудований USB-JTAG або FT2232",
  "openocd -f interface -f target",
  "break / step / bt / info threads",
  "Secure Boot закриє JTAG назавжди!"]),
"partitions-nvs-layout-scheme.png": ("Partitions + NVS",
 ["0x8000: partition-table окремо!",
  "factory + ota_0 + ota_1 + otadata",
  "nvs + phy_init + coredump + spiffs",
  "CSV своя; erase після зміни!",
  "NVS: key-value, wear-leveling"]),
"filesystem-littlefs-fat-scheme.png": ("Файлові системи",
 ["LittleFS — дефолт всередині (не SPIFFS!)",
  "FATFS — SD-карти, великі файли",
  "Монтування при старті; форматування раз",
  "Знос: логи кільцем, не дописуванням",
  "OTA-образ НЕ тримати у тій самій ФС"]),
"ota-dualbank-rollback-scheme.png": ("OTA: два слоти + відкат",
 ["Писати в НЕАКТИВНИЙ слот!",
  "verify + SHA → boot → self-test",
  "Провал self-test → rollback назад",
  "otadata лічильник спроб",
  "Два банки + Jobs для парку"]),
"secureboot-flashenc-scheme.png": ("Secure Boot + шифрування",
 ["eFuse: ключі горять НАЗАВЖДИ!",
  "Boot V2: RSA/ECDSA-підпис app",
  "Flash Encryption: XTS-AES прозоро",
  "Anti-rollback: версія тільки вгору",
  "Тренуватись на жертовному модулі!"]),
"gpio-overview-matrix-scheme.png": ("GPIO: матриця, струми, blink",
 ["34 піни; безпечні: 13,14,18,19,21–23",
  "Matrix: периферія на будь-який пін!",
  "Макс 12 мА/пін, сумарно ~40 мА",
  "LED тільки через 220 Ом / драйвер!",
  "5V на GPIO = смерть кристала!"]),
"gpio-strapping-boot-scheme.png": ("Strapping: GPIO0/2/5/12/15",
 ["GPIO0 LOW = download-режим!",
  "GPIO2: не вгору при boot (S3: RGB!)",
  "GPIO12 MTDI: не вгору (flash!)",
  "GPIO15 MTDO: debug-повідомлення",
  "10к pull — норма; без висячих!"]),
"gpio-pullup-levels-scheme.png": ("Pull-up/down і рівні 3.3V/5V",
 ["Внутрішні ~45к: слабкі для I2C!",
  "I2C: зовнішні 4.7к до 3.3V!",
  "5V сенсор → дільник або TXS0108!",
  "Кнопка: до GND + pull-up (активний LOW)",
  "Довгі лінії: 2.2к + 100нФ фільтр"]),
"gpio-interrupt-pwm-scheme.png": ("Переривання + PWM/LEDC",
 ["attachInterrupt: RISING/FALLING/CHANGE",
  "ISR: IRAM + без delay/Serial!",
  "Дебаунс 20–50 мс таймером, не delay!",
  "LEDC: частота + розрядність + канал",
  "Серво 50 Гц; мотор — через драйвер!"]),
"gpio-rtc-sleep-scheme.png": ("RTC-GPIO: hold + ULP + сон",
 ["RTC-піни тримають рівень у сні (hold)!",
  "ULP будить по АЦП/тачу порогу",
  "EXT0: один пін; EXT1: маска пінів",
  "Touch-wake: поріг калібрувати!",
  "Прокинувся → причина → дія → сон"]),
"cloud-platforms-firebase-shelly-scheme.png": ("Хмара: Firebase/Shelly/Frigate/Supabase",
 ["Firebase: RTDB + FCM через Function",
  "Shelly: HTTP-RPC по LAN, без хмари!",
  "Frigate: події person/car по MQTT",
  "Supabase: REST-рядок + RLS!",
  "Domoticz: MQTT domoticz/in + idx",
  "Prometheus: scrape /metrics 60с"]),
"usb-pd-trigger-profiles-scheme.png": ("USB-PD: тригер і профілі",
 ["5V за Rd 5.1к — дефолт завжди",
  "CH224K: джампер 9/12/15/20V",
  "Мультиметр ДО плати! TVS + запобіжник",
  "Тільки C–C кабель з CC-жилами!",
  "FUSB302 — тільки серія + RT-задача"]),
"fuel-gauge-soc-scheme.png": ("Fuel gauge: чесні відсотки",
 ["Дільник бреше: плоска середина!",
  "MAX17048: без шунта, I2C 0x36",
  "LC709203: APA-профіль під банку!",
  "BQ27441: DesignCap = паспорт мАг",
  "ALRT → wake; 50 мкА в бюджет!"]),
"tpl5110-nanotimer-power-scheme.png": ("TPL5110: 35 нА замість сну",
 ["MOSFET рубає живлення цілком!",
  "DONE після роботи — не чекати!",
  "RAM чиста: стан тільки в NVS!",
  "Інтервал резистором з даташиту",
  "OTA тільки з джампером (без TPL!)"]),
"lpwan-alt-compare-scheme.png": ("LPWAN: LoRa vs Sigfox/NB/MIOTY",
 ["LoRa: свій шлюз, без абонплати",
  "Sigfox: 12 байт + оператори гаснуть!",
  "NB-IoT: тариф + TCO на 5 років",
  "MIOTY: цех з multipath",
  "Свій шлюз першим, вузли потім"]),
"uwb-dw3000-ranging-scheme.png": ("UWB-2: DW3000, TDoA/PDOA",
 ["DW1000 — NRND; нові тільки DW3000!",
  "Канали тільки 5 і 9!",
  "DS-TWR ±5–10 см; калібрувати delay!",
  "PDOA: тільки двоантенна плата",
  "TDoA: теги блимають, якорі в sync"]),
"lorawan-gateway-sx1302-scheme.png": ("LoRaWAN-шлюз: SX1302 + TTN",
 ["Single-channel — тест, не мережа!",
  "SX1302: 8 каналів + downlink",
  "Антена якомога вище!",
  "ABP: frame-counter тільки в NVS!",
  "Backhaul: Ethernet; поле — Cat-1"]),
"esp32-lorawan-gateway-deep-scheme.png": ("LoRaWAN-шлюз глибоко",
 ["8 каналів SF7-SF12 одночасно",
  "TTN: DevEUI/AppKey, FCnt-дедуп",
  "Антена вище, коаксіал коротше",
  "Живлення 5V 3A + сонце/PoE",
  "Heartbeat в MQTT кожні 5 хв"]),
"tinym-deep-scheme.png": ("TinyML-deep: конвеєр Edge-AI",
 ["Дані 2-5 год → PTQ int8 → .tflite",
  "C3: I2S-мікрофон, 16 кГц, інференс <30 мс",
  "S3: OV2640 + PSRAM, 96×96, 8-12 кадрів/с",
  "Аудіо: 3.3 В тільки! (INMP441)",
  "Калібрування — на робочих умовах!",
  "Сон між циклами: батарея місяцями"]),
"c5c61-robot-scheme.png": ("C5/C61-робот: два вузли",
 ["C5: мозок — LEDC, ПІД 1 кГц, енкодери",
  "C61: очі — VL53L0X + BME280 → MQTT",
  "DRV8833: VMOT з батареї, не з 3.3 В!",
  "LDO 6 В→3.3 В: ME6211 (AMS1117 гріється)",
  "Енкодер: переривання ×4, знак перевірити!",
  "WiFi 6 5 ГГц: тільки C5, C61 — 2.4 ГГц!"]),
"esp32-p4-devkit-scheme.png": ("P4 Function EV Board: хост",
 ["P4: 2x RISC-V 400 МГц, радіо нема!",
  "MIPI-CSI/DSI + H.264 енкодер",
  "USB-OTG HS + Serial-JTAG в одному",
  "Радіо — C6 поруч по SDIO/SPI",
  "Живлення 5 В 2 А, P4 гріється!",
  "IDF 5.3+, set-target esp32p4"]),
"esp32-c5-devkit-scheme.png": ("C5 DevKitC: dual-band WiFi 6",
 ["WiFi 6: 2.4 + 5 ГГц одночасно",
  "802.15.4: Zigbee/Thread/Matter",
  "BAND_AUTO, 5 ГГц — 36-48 канали",
  "LP-CPU 40 МГц збирає в сні",
  "5 ГГц пік струму: живи чесно!",
  "Arduino-core 3.3+, IDF 5.5+"]),
"esp32-thermal-mlx90640-scheme.png": ("MLX90640: тепловий зір",
 ["32x24 пікселі, ±1 градус",
  "I2C 1 МГц, адреса 0x33",
  "EEPROM читати раз при старті",
  "Поріг людини: медіана + 5!",
  "Пожежка: 80 градусів 3 кадри",
  "Кадр 4 Гц, дисплей — інтерполяція"]),
"esp32-usb-host-scheme.png": ("ESP32 USB-хост: TinyUSB",
 ["S3: D-/D+ GPIO19/20, P4 — HS",
  "VBUS 5 В: хост живить пристрій!",
  "MSC: флешка FATFS, закривай файл",
  "HID: довжину репорту з дескриптора",
  "CDC: модеми AT поверх USB",
  "Disconnect-колбек, інакше паніка"]),
"esp32-matter-thread-deep-scheme.png": ("Matter-over-Thread глибоко",
 ["Вузол: C6/H2, приклад light",
  "Комісія: QR + BLE поруч",
  "NVS з ключами — святе!",
  "BR 24/7: Thread в IP",
  "Multi-admin — фішка, не баг"]),
"esp32-p4-native-scheme.png": ("P4 нативно: MIPI+H.264",
 ["MIPI: шлейф + SCCB-таблиця",
  "Кадри тільки в PSRAM!",
  "H.264: GOP щосекунди",
  "USB-HS: 5V на VBUS",
  "Радіо — завжди C6 ззовні"]),
"esp32-ethernet-poe-deep-scheme.png": ("Ethernet + PoE глибоко",
 ["SPI 40 МГц, шлейф до 10 см",
  "Статика замість DHCP 24/7",
  "PoE тільки активний af/at",
  "Сокети закривати з таймаутом",
  "WiFi — резерв, не основа"]),
"esp32-usb-uvc-deep-scheme.png": ("USB-UVC: камери",
 ["5V VBUS з запасом струму!",
  "MJPEG 640x480 — старт",
  "Колбек короткий, черга далі",
  "Passthrough без декоду",
  "AVI-індекс фіналізувати"]),
"esp32-lvgl-widgets-deep-scheme.png": ("LVGL: віджети кодом",
 ["tick 5 мс — серцебиття",
  "Один потік або м'ютекс!",
  "Шрифт з кирилицею одразу",
  "Буфер частковий в SRAM",
  "Графіки не частіше 10 Гц"]),
"esp32-edge-ai-vision-scheme.png": ("Edge-AI зір: трекінг",
 ["Модель int8, поріг 0.6",
  "IoU 0.3, вік треку 10",
  "ROI вирізає сміття",
  "PIR будить, сон економить",
  "Ніч = NoIR + ІЧ"]),
}

def draw(name, title, lines):
    Ft, Fs, Fm, Ff = fonts()
    W, H = 1000, 200 + len(lines) * 44 + 120
    H = max(H, 520)
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, W, 130], fill=(17, 42, 67))
    d.text((30, 22), "ESP32-Reference", font=Fs, fill=(125, 211, 252))
    d.text((30, 55), title, font=Ft, fill="white")
    y = 150
    d.rectangle([0, y - 34, W, y + 2], fill=(255, 251, 235))
    d.text((30, y - 30), "3.3V логіка!  5V на GPIO — смерть кристала.", font=Ff, fill=(146, 64, 14))
    y += 30
    for ln in lines:
        d.text((30, y), "•  " + ln, font=Fm, fill=(17, 24, 39))
        y += 44
    d.rectangle([0, H - 56, W, H], fill=(241, 245, 249))
    d.text((30, H - 42), "ESP32-Reference  •  згенеровано локально (без копійованих картинок)",
           font=Ff, fill=(100, 116, 139))
    img.save(os.path.join(OUT, name))

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for n, (t, ls) in C.items():
        draw(n, t, ls)
    print(f"generated {len(C)} png")
