#!/usr/bin/env python3
"""Генерація wiring/pinout PNG для RaspberryPi-Reference. Оригінальні схеми, без копійованих картинок."""
import os
from PIL import Image, ImageDraw, ImageFont

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "img")
FB = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FM = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

def fonts():
    return (ImageFont.truetype(FB, 40), ImageFont.truetype(FB, 24),
            ImageFont.truetype(FM, 22), ImageFont.truetype(FR, 20))

# name: (заголовок, [рядки схеми])
C = {
"rpi-start-map-scheme.png": ("Карта стартових маршрутів",
 ["Новачок: плата → Imager → LED",
  "Мейкер: GPIO → шини → HAT",
  "IoT: WiFi → MQTT → хмара",
  "3.3V логіка — святе!",
  "Валідатори: style/links/home в нуль"]),
"rpi-glossary-scheme.png": ("Глосарій: карта термінів",
 ["SoC → плата → гребінка → HAT",
  "GPIO → I2C/SPI/UART → датчики",
  "CSI — камера, DSI — дисплей",
  "OS → gpiozero → MQTT",
  "Незнайоме слово — сюди!"]),
"rpi-models-compare-scheme.png": ("Моделі: хто є хто",
 ["Pi 5: флагман, PD 27W, кулер!",
  "Pi 4: робоча конячка 3A",
  "Zero 2 W: малюк з Linux",
  "Pico: MCU, Linux нема!",
  "CM: серія + плата-носій"]),
"rpi-boards-choice-scheme.png": ("Комплект з першого разу",
 ["Офіційний БЖ — не маркетинг!",
  "SD A2, перевірка f3",
  "Pi 5 без кулера тротлить!",
  "Шлейфи CSI/DSI: запасний у сумці",
  "HAT — після запуску, не про запас"]),
"rpi-os-choice-scheme.png": ("ОС і середовище",
 ["Desktop — від 2 ГБ RAM",
  "Lite/DietPi — сервери і Zero",
  "Pico: MicroPython або C SDK",
  "Imager: SSH+WiFi в одному вікні",
  "venv на кожен Python-проєкт"]),
"rpi-soc-oglyad-scheme.png": ("SoC: еволюція кристалів",
 ["BCM2835 → BCM2712: A76!",
  "VideoCore IV → VII, Vulkan",
  "RP1: периферія Pi 5 окремо",
  "RP2040/50: PIO, не Linux",
  "RTC з батарейкою — вперше!"]),
"rpi-bcm2712-pi5-scheme.png": ("BCM2712 + Pi 5: швидкість",
 ["4xA76 + L3, LPDDR4X-4267",
  "PCIe x1: NVMe 500 МБ/с",
  "RP1 по PCIe x4 без заторів",
  "PD 27W, USB 1.2A сумарно",
  "Кулер обов'язковий 24/7!"]),
"rpi-rp2040-rp2350-scheme.png": ("RP2040/RP2350: PIO-сила",
 ["PIO: WS2812/I2S/DVI фоном",
  "АЦП 12 біт + VSYS/4 батарея",
  "USB: пристрій (2350: +хост)",
  "Сон — мікроампери, GPIO-будильник",
  "W-версії: тільки 2.4 ГГц!"]),
"rpi-pi5-board-scheme.png": ("Pi 5 як виріб",
 ["NVMe-HAT через FPC",
  "RTC-JST + FAN-JST роз'єми",
  "Кнопка живлення + UART-консоль",
  "dtparam=pciex1 для диска",
  "Корпус з кулером, не глухар!"]),
"rpi-pi4-board-scheme.png": ("Pi 4: робоча конячка",
 ["Ревізії 1.4+: USB-C виправлено",
  "2xUSB3: SSD без хаба",
  "4Kp60 тільки з HDMI0",
  "Gigabit чесний, не через USB",
  "Радіатор мінімум!"]),
"rpi-pico-family-scheme.png": ("Pico-родина: 4 плати",
 ["BOOTSEL + UF2 перетягуванням",
  "WL-LED через CYW43, не GPIO25!",
  "Thonny: REPL і плоттер",
  "Picoprobe: SWD за 4 долари",
  "Антена — не закривати металом"]),
"rpi-zero2w-board-scheme.png": ("Zero 2 W: малюк",
 ["PWR і OTG — різні порти!",
  "Headless: Imager + SSH",
  "OTG-хаб з живленням",
  "512 МБ: тільки Lite!",
  "Унікальний hostname кожному"]),
"rpi-cm4-cm5-scheme.png": ("CM4/CM5: серія",
 ["eMMC замість SD для серії",
  "rpiboot: модуль як диск",
  "IO Board — еталон носія",
  "Антена: доріжка або U.FL",
  "A/B-розділи + відкат в полі"]),
"rpi-400-500-scheme.png": ("400/500: ПК у клавіатурі",
 ["Усе всередині, монитор + миша",
  "GPIO-вікно знизу + шлейф",
  "HATи не сідають — макетка!",
  "NVMe нема, тільки USB-диски",
  "Школа: Scratch → Thonny → VS Code"]),
"rpi-imager-headless-scheme.png": ("Imager + headless",
 ["Модель + образ + карта",
  "SSH + WiFi + юзер в майстрі",
  "Країна WiFi — інакше нема 5 ГГц",
  "throttled=0x0 — живлення ок",
  "Бекап образу раз на місяць"]),
"rpi-eeprom-boot-scheme.png": ("EEPROM-boot: порядок",
 ["BOOT_ORDER справа наліво",
  "0xf14: SD, потім USB",
  "NVMe: pciex1 + свіжий EEPROM",
  "recovery.bin: зелений = ок",
  "Дистанційно — тільки з KVM"]),
"rpi-os-nalashtuvannya-scheme.png": ("ОС після старту",
 ["config.txt: мінімум чіпати",
  "systemd, не rc.local!",
  "venv: системний Python святий",
  "ufw + fail2ban назовні",
  "throttled ≠ 0 — міняти БЖ"]),
"rpi-usb-c-pd-scheme.png": ("Живлення: БЖ і просадки",
 ["Pi 5: PD 27W, інакше USB 600 мА",
  "Кабель короткий і товстий!",
  "throttled=0x0 — живлення ок",
  "USB-диски через хаб з живленням",
  "Прапорець пам'ятає просадку!"]),
"rpi-docker-systemd-scheme.png": ("Docker на Pi", ["docker/run", "volume/systemd", "ARM image", "compose.yaml"]),
"rpi-poe-hat-scheme.png": ("PoE HAT: вати по витій парі",
 ["Тільки активний af/at!",
  "Кабель 4 пари, до 100 м",
  "Порт PoE увімкнути на світчі!",
  "Кулер HATа: шум рахувати",
  "Пасивні вольти — смерть входу"]),
"rpi-ups-18650-scheme.png": ("UPS: резерв на 18650",
 ["Шапка на 3A + захищені банки",
  "Shutdown-скрипт з гістерезисом",
  "Суперконденсатор — на моргання",
  "Бекап SD до сезону блекаутів",
  "Тест висмикуванням щокварталу"]),
"rpi-header-gpiozero-scheme.png": ("Гребінка 40 + gpiozero",
 ["BCM-номери, не фізичні!",
  "3.3V: 5V на вхід — смерть",
  "LED: GPIO17 + 330 Ом",
  "Кнопка: на землю + pull-up",
  "ID-піни 27/28 святі!"]),
"rpi-pwm-pererivannya-scheme.png": ("ШІМ і переривання",
 ["Апаратний ШІМ: 12/13/18/19",
  "Серво: 50 Гц, живлення окремо",
  "Колбек короткий, робота в потоці",
  "lgpio замість повільної фабрики",
  "bounce_time 20-50 мс"]),
"rpi-hat-eeprom-scheme.png": ("HAT + EEPROM",
 ["Справжній HAT = EEPROM!",
  "ID-піни тільки для EEPROM",
  "Оверлеї в config.txt",
  "Адреси перевірити до покупки",
  "3.3V з плати — до 500 мА"]),
"rpi-i2c-spi-uart-scheme.png": ("Шини: I2C/SPI/UART",
 ["i2cdetect -y 1 — перша команда",
  "I2C підтяжки вже на платі",
  "SPI: швидкість ставить код",
  "UART: консоль геть для модема",
  "Аналізатор при мовчанні!"]),
"rpi-logic-analyzer-scheme.png": ("Аналізатор: бачити шини",
 ["GND аналізатора на землю плати!",
  "Захват 8x від швидкості шини",
  "Тригер по старту пакета",
  "Декодер показує ACK/NACK",
  "Живлення аналізатора — з ПК"]),
"rpi-sd-emmc-nvme-scheme.png": ("Носії: SD→NVMe",
 ["SD тільки A2 + перевірка f3",
  "NVMe: pciex1 + свіжий EEPROM",
  "TRIM щотижня для SSD",
  "Логи в RAM, не на SD",
  "Система — на найживучішому"]),
"rpi-backup-clone-scheme.png": ("Бекапи: 3 рівні",
 ["Золотий образ + sha256",
  "Дані rsync щодня, 7 зрізів",
  "Тест відновлення щокварталу",
  "2 копії в різних місцях",
  "Ім'я образу з датою"]),
"rpi-bme280-klimat-scheme.png": ("BME280: клімат одним чипом",
 ["SDA/SCL: піни 3/5",
  "SDO на землю = 0x76",
  "QNH оновлювати щодня",
  "Forced-режим для батареї",
  "CSV + MQTT одразу"]),
"rpi-mpu6050-rukh-scheme.png": ("MPU6050: кути без дрейфу",
 ["PWR_MGMT_1 = 0: розбудити!",
  "Нуль гіро — 200 вимірів",
  "Фільтр: 0.98 гіро + 0.02 аксель",
  "Цикл 50 Гц вистачає Python",
  "Знаковий переклад int16!"]),
"rpi-ds18b20-temp-scheme.png": ("DS18B20: шина 1-Wire",
 ["Один GPIO + 4.7 кОм!",
  "w1-gpio оверлей в config.txt",
  "Читати як файли, дивитись YES",
  "3 дроти замість паразитних",
  "Аліаси в конфігу, не в коді"]),
"rpi-ina219-strum-scheme.png": ("INA219: вати по I2C",
 ["Калібрування першим рядком!",
  "Шунт у плюсі, земля спільна",
  "Алерт на GPIO з перериванням",
  "Журнал з flush()",
  "Адреси 0x40-0x4F перемичками"]),
"rpi-gps-neo-scheme.png": ("GPS NEO: небо і час",
 ["Антена бачить небо!",
  "TX→RX перехресно",
  "Консоль геть з UART0",
  "Парсити тільки валідні кадри",
  "PPS — точний час Chrony"]),
"rpi-kamera-csi-scheme.png": ("Камера CSI: Picamera2",
 ["Шлейф синім до роз'єму!",
  "Bookworm = тільки Picamera2",
  "list-cameras — перша команда",
  "Пауза на автофокус",
  "Таймлапс + ffmpeg-склейка"]),
"rpi-dsi-hdmi-displeyi-scheme.png": ("Дисплеї: DSI/HDMI/SPI",
 ["DSI: живлення за мануалом!",
  "HDMI0 — основний 4K",
  "Поворот: екран і тач окремо",
  "Кіоск: автологін + systemd",
  "SPI — прилади, не відео"]),
"rpi-neopixel-servo-rele-scheme.png": ("Сила: світло/рух/220V",
 ["Земля спільна завжди!",
  "NeoPixel: конденсатор + резистор",
  "Серво: живлення окремо",
  "220V: корпус + клеми + запобіжник",
  "Яскравість 0.3 береже очі"]),
"rpi-audio-hat-scheme.png": ("Аудіо: I2S/USB/мікрофон",
 ["I2S HAT: overlay + aplay -l",
  "USB: udev-фіксація індексу",
  "alsactl store рівні",
  "Голос: Vosk + Piper офлайн",
  "Мультирум: Snapcast по дроту"]),
"rpi-wifi-bt-bort-scheme.png": ("Бортове радіо",
 ["Країна WiFi — першим рядком!",
  "AP: nmcli hotspot за хвилину",
  "PM вимкнути для 24/7",
  "Антена не в металі",
  "brcmfmac логи — перше джерело"]),
"rpi-adc-zovnishnye-scheme.png": ("АЦП ззовні: ADS/MCP",
 ["Точність — ADS1115, швидкість — MCP",
  "Калібрування за TL431",
  "RC-фільтр на вході завжди",
  "Усереднення: медіана + середнє",
  "Земля зіркою!"]),
"rpi-taimeri-son-scheme.png": ("Час і сон вузла",
 ["cron — хвилини, systemd — секунди",
  "Watchdog увімкнений на 24/7!",
  "flock проти подвійних запусків",
  "Pico спить між вимірами",
  "RTC-будильник для розкладу"]),
"rpi-sense-hat-scheme.png": ("Sense HAT: легенда",
 ["Матриця 8x8 + low_light",
  "IMU + тиск + вологість",
  "Джойстик подіями, не опитуванням",
  "Температура з датчика тиску!",
  "Емулятор sense-emu без плати"]),
"rpi-gps-lora-hat-scheme.png": ("LoRa + GPS HAT",
 ["SF9/BW125 — стартовий профіль",
  "Антена до вмикання TX!",
  "GPS: небо + активна антена",
  "Шлюз приймає, вузли сплять",
  "Діапазони за законом!"]),
"rpi-can-rs485-hat-scheme.png": ("CAN/RS485 HAT",
 ["Термінатори 120 Ом на кінцях!",
  "Бітрейт один на всіх",
  "DE/RE — GPIO з затримкою",
  "Ізоляція в щитах обов'язкова",
  "Спочатку слухаємо, потім пишемо"]),
"rpi-buck-boost-dc-dc-scheme.png": ("DC-DC: поле і авто",
 ["Налаштування під навантаженням!",
  "Запас струму 50 %",
  "LC-фільтр на виході завжди",
  "Запобіжник + TVS на вході",
  "Сонце тільки через MPPT"]),
"rpi-level-shift-3v3-scheme.png": ("Рівні 3.3V: міст",
 ["Вхід плати: ніколи вище 3.6V!",
  "I2C — MOSFET-зсув король",
  "Дільник тільки сигнал, не живлення!",
  "Перевірка петлею до датчика",
  "OE і живлення за порядком"]),
"rpi-mqtt-broker-scheme.png": ("MQTT: брокер на платі",
 ["Локальний брокер = автономність",
  "set — команди, state — retained",
  "LWT про смерть клієнта",
  "Унікальний ID на вузол",
  "Паролі в окремий файл"]),
"rpi-http-webhook-scheme.png": ("HTTP і вебхуки",
 ["Flask слухає LAN, не світ!",
  "Вебхуки з чергою і тротлінгом",
  "Секрети в файлах 600",
  "gunicorn для 24/7",
  "Зовні — тільки через VPN"]),
"rpi-meteostantsiya-scheme.png": ("Метеостанція повністю",
 ["Щогла 2-3 м + екран Стівенсона",
  "Калібрування з паспортів",
  "Передача раз на 5 хвилин",
  "Живлення з запасом х2",
  "Чистка лійки восени"]),
"rpi-gps-treker-scheme.png": ("GPS-трекер",
 ["Антена назовні завжди!",
  "Тільки валідні кадри",
  "Стоянка — пауза запису",
  "Канал за покриттям",
  "Відсічка АКБ 11.8V"]),
"rpi-robot-vizok-scheme.png": ("Робот-візок: два мозки",
 ["Pi думає, Pico крутить",
  "Живлення сили окремо!",
  "Три контури безпеки",
  "Енкодери — пряма без сюрпризів",
  "Спочатку телеоп, потім авто"]),
"rpi-priladi-lab-scheme.png": ("Прилади: драбина",
 ["Мультиметр → тестер → аналізатор",
  "Земля першою завжди!",
  "Струм з 10A-гнізда",
  "220V — кліщі/дифпробник",
  "Стенд після кожної зміни"]),
"rpi-plata-pcb-hat-scheme.png": ("Своя плата HAT",
 ["ERC/DRC в нуль до заводу!",
  "Земля суцільна, живлення широке",
  "BOM з Mfr_PN на все",
  "Дим-тест за протоколом",
  "5 штук: вбити/робота/запас"]),
}

def draw(name, title, lines):
    Ft, Fs, Fm, Ff = fonts()
    W, H = 1000, 200 + len(lines) * 44 + 120
    H = max(H, 520)
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, W, 130], fill=(165, 0, 52))
    d.text((30, 22), "RaspberryPi-Reference", font=Fs, fill=(255, 255, 255))
    d.text((30, 55), title, font=Ft, fill="white")
    y = 150
    d.rectangle([0, y - 34, W, y + 2], fill=(255, 251, 235))
    d.text((30, y - 30), "3.3V logika! 5V na GPIO — smert plata.", font=Ff, fill=(146, 64, 14))
    y += 30
    for ln in lines:
        d.text((30, y), "•  " + ln, font=Fm, fill=(17, 24, 39))
        y += 44
    d.rectangle([0, H - 56, W, H], fill=(241, 245, 249))
    d.text((30, H - 42), "RaspberryPi-Reference  •  zgenerovano lokalno (bez kopiiovanykh kartynok)",
           font=Ff, fill=(100, 116, 139))
    img.save(os.path.join(OUT, name))

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for n, (t, ls) in C.items():
        draw(n, t, ls)
    print(f"generated {len(C)} png")
