#!/usr/bin/env python3
"""Генерація wiring/pinout PNG для STM32-Reference. Оригінальні схеми, без копійованих картинок."""
import os
from PIL import Image, ImageDraw, ImageFont

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "img")
FB = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FM = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

def fonts():
    return (ImageFont.truetype(FB, 40), ImageFont.truetype(FB, 24),
            ImageFont.truetype(FM, 22), ImageFont.truetype(FR, 20))

# name: (заголовок, [рядки схеми])
C = {
"stm32-f0-f1-classic-scheme.png": ("F0/F1 — класика і Blue Pill",
 ["2.0–3.6V, 5V-толерантні — тільки за даташитом", "BOOT0=1 — заводський bootloader",
  "USB тільки в F072/F105!", "Float — програмно, повільно!"]),
"stm32-f3-f4-perf-scheme.png": ("F3 — аналог, F4 — швидкість",
 ["F3: АЦП 5 Msps + компаратори + ЦАП", "F4: FPU + DCMI + LTDC",
  "VDDA окремо, інакше шум!", "USB — тільки з кварцом HSE"]),
"stm32-g0-g4-modern-scheme.png": ("G0 — дешево, G4 — аналог-монстр",
 ["G0B1 — USB-C PD", "G4: 5× АЦП + ОУ + HRTIM 184 пс",
  "АЦП калібрувати при старті", "VREFBUF увімкнути!"]),
"stm32-h5-h7-flagship-scheme.png": ("H5/H7 — флагмани",
 ["TrustZone — H5/H735, не старий H743!", "H750 — без внутрішньої Flash!",
  "VCAP-конденсатори обов'язкові", "Домени D1/D2/D3 — читати PWR!"]),
"stm32-l0-l4-u5-lowpower-scheme.png": ("L0/L4/U5 — батарея на роки",
 ["Найглибший сон, який дозволяє задача", "EEPROM пише при зміні, не в циклі!",
  "LPBAM — периферія без CPU (U5)", "Міряй реальний сон амперметром!"]),
"stm32-wb-wl-radio-scheme.png": ("WB/WL — два ядра, одне радіо",
 ["M4 — твій код, M0+ — стек", "Спочатку FUS, потім stack, потім код!",
  "Антена 50 Ом на свою частоту", "Пам'ять ділиться зі стеком!"]),
"bluepill-power-scheme.png": ("Blue Pill — живлення і прошивка",
 ["5V (USB) ──► RT9193 → 3.3V (слабкий!)", "GND ─── GND",
  "SWDIO ──► GPIO14 (PA13)", "SWCLK ──► GPIO15 (PA14)",
  "BOOT0 jumper: 0 = Flash, 1 = System (DFU)", "NRST ──► кнопка до GND"]),
"stm32-families-compare-scheme.png": ("Родини STM32 — вибір за задачею",
 ["G0/F1 — кнопки і реле", "F3/G4 — аналог і виміри",
  "F4/H7 — дисплей і швидкість", "L0/L4/U5 — батарея на роки",
  "WB/WL — радіо з коробки", "Errata читати ДО плати!"]),
"stm32-env-choose-scheme.png": ("Середовище — CubeIDE / Arduino / PIO",
 ["Arduino — старт за вечір", "CubeIDE + HAL — серійний виріб",
  "PlatformIO — команда і CI", "HAL — повільно, LL — гаряче",
  "Свій код тільки між USER CODE!"]),
"stm32-devkit-boards-scheme.png": ("Плати — Blue Pill / Nucleo / Discovery",
 ["Blue Pill $2 + зовнішній ST-Link", "Nucleo — дебаг з коробки",
  "Клони: перевірити маркування!", "BOOT0 назад у 0!"]),
"stm32-glossary-terms-scheme.png": ("Словник STM32 — шари і терміни",
 ["HAL — зручно, LL — швидко", "CMSIS + SVD — база і дебаг",
  "SWD — 2 дроти прошивки", "RDP-2 — назавжди, не чіпати!"]),
"stm32-howto-map-scheme.png": ("Карта довідника — куди йти",
 ["Home — вхід", "Розділи 00–99 — теми",
  "Нота: призначення → код → помилки", "Не знайшов за 5 хв — пошук!"]),
"stm32-cubeide-project-scheme.png": ("CubeIDE — .ioc у прошивку",
 [".ioc кліки ──► генерація коду", "Свій код ТІЛЬКИ між USER CODE!",
  "Clock tree налаштувати свідомо", "Зелений жук = Debug, GDB всередині"]),
"stm32-hal-ll-layers-scheme.png": ("HAL vs LL — шари коду",
 ["HAL — зручно, повільно, переносимо", "LL — тонкі інлайни, гаряче в ISR!",
  "Одна периферія — один шар", "MSP: піни і NVIC ховаються там"]),
"stm32-stlink-flash-scheme.png": ("ST-Link — прошивка і дебаг",
 ["SWDIO + SWCLK + GND + NRST", "Connect under reset рятує цеглу",
  "CubeProgrammer: erase + verify!", "RDP-2 — назавжди, не чіпати!"]),
"stm32-toolchain-alt-scheme.png": ("Без CubeIDE — VSCode + CMake",
 ["CubeMX ──► код, збірка ──► CMake/Ninja", "st-flash / OpenOCD заливають",
  "Той самий HAL/LL, інший редактор", "CI збирає headless-варіантом"]),
"stm32-gpio-modes-scheme.png": ("GPIO — режими і регістри",
 ["MODER: in / out / AF / analog", "OTYPER: PP або OD + PUPDR!",
  "BSRR: атомарно, без RMW", "FT — 5V ок, інші — ні!"]),
"stm32-af-mapping-scheme.png": ("AF — функції на пінах",
 ["Один пін — одна функція!", "AFRL/AFHR: AF0–AF15", "F1: remap через MAPR",
  "SWD-піни не чіпати!"]),
"stm32-exti-nvic-scheme.png": ("EXTI + NVIC — переривання",
 ["EXTI0: PA0 або PB0 — один!", "SYSCFG мапить порт", "Пріоритети: preempt + sub",
  "Дребезг — RC або таймер!"]),
"stm32-uart-scheme.png": ("UART — TX/RX + DMA-idle",
 ["BRR від точної шини!", "DMA circular + idle = пакети", "ORE/FE/NE — читати прапорці",
  "RS485: DE-таймінги!"]),
"stm32-spi-scheme.png": ("SPI — master, NSS, DMA",
 ["CPOL/CPHA: 4 режими, у всіх однакові!", "NSS вести самому або залізом",
  "DMA: TX і RX разом!", "Дисплей: DC-пін окремо!"]),
"stm32-i2c-scheme.png": ("I2C — адреса, ACK, pull-up",
 ["Pull-up 2.2–4.7k, інакше сходинки", "Clock-stretch: слейв чекає", "NACK = нема девайса",
  "Зависла шина: 9 клоків SCL!"]),
"stm32-fdcan-scheme.png": ("FD-CAN — фільтри і таймінг",
 ["Sample point 75–87%!", "Фільтри: mask або list", "120 Ом на кінцях",
  "bxCAN — mailbox, FDCAN — MRAM!"]),
"stm32-usb-scheme.png": ("USB — CDC/HID/MSC/DFU",
 ["D+ pull-up 1.5k — інакше невидимка", "Дескриптори: device/cfg/ep", "PMA на F1 — рахувати!",
  "DFU: BOOT0=1 + USB!"]),
"stm32-sdmmc-qspi-scheme.png": ("SDMMC + QUADSPI — карти",
 ["SDMMC: 4 біти + DMA", "QSPI XIP: код ззовні!", "Dummy cycles за даташитом",
  "Доріжки короткі і рівні!"]),
"stm32-adc-scheme.png": ("АЦП — канали і DMA",
 ["VDDA окремо, інакше шум!", "Sampling time під джерело", "Калібрування при старті!",
  "DMA: скан без CPU"]),
"stm32-dac-scheme.png": ("ЦАП — хвилі через DMA",
 ["DMA + тригер таймера = синус", "Буфер при навантаженні!", "Шум/трикутник залізом"]),
"stm32-comp-opamp-scheme.png": ("Компаратори і ОУ",
 ["COMP → BKIN: стоп ШІМ!", "OPAMP PGA: без зовнішніх", "Гістерезис проти дребезгу"]),
"stm32-dfsdm-scheme.png": ("DFSDM — сигма-дельта",
 ["Мікрофон PDM напряму!", "Sinc-фільтр залізом", "Шунт струму точно"]),
"stm32-gptim-adtim-scheme.png": ("Таймери — ШІМ і захист",
 ["PSC+ARR = частота", "Complementary + dead-time", "Break: гасить все залізо!"]),
"stm32-lptim-rtc-wdt-scheme.png": ("LPTIM/RTC/WDT — час",
 ["LPTIM цокає у Stop!", "RTC: VBAT + LSE-кварц", "IWDG — остання надія"]),
"stm32-sleep-modes-scheme.png": ("Сон — режими і струми",
 ["Найглибший, який можна!", "RAM: що виживає?", "Пробудження: EXTI/RTC",
  "Дебагер не дає спати!"]),
"stm32-power-rails-scheme.png": ("Живлення — домени",
 ["VDDA + VREF для аналогу", "VCAP на H7 обов'язково!", "PVD/BOR ловлять просадку",
  "Декуплінг біля кожного VDD"]),
"stm32-battery-scheme.png": ("Батарея — хімії і заряд",
 ["Li-SOCl2: роки без заряду", "VBAT тримає RTC!", "Fuel-gauge, не вольтметр"]),
"stm32-dht-ds18b20-scheme.png": ("DHT11/DS18B20 — таймінги",
 ["DHT: старт 18 мс + 40 біт", "DS18B20: 1-Wire + CRC!", "Таймер мікросекунд, не delay!"]),
"stm32-bme-sht-scheme.png": ("BME/SHT — I2C-датчики",
 ["Адреса + регістри (mem-read!)", "Калібрування з OTP", "BME280 ≠ BMP280: вологість!"]),
"stm32-mpu-imu-scheme.png": ("MPU/IMU — рух",
 ["DMP або свій Маджвік", "Опитування 1 кГц + DMA", "Калібрування гіроскопа!"]),
"stm32-ina-hx711-scheme.png": ("INA/HX711 — струм і вага",
 ["Шунт + PGA-підсилення", "HX711: 24 біти повільно", "Тара при старті!"]),
"stm32-hcsr-vl53-scheme.png": ("Дистанція — ультразвук і ToF",
 ["Echo: capture ширини!", "VL53L0X: I2C + XSHUT", "Сліпа зона HC-SR04!"]),
"stm32-oled-ssd1306-scheme.png": ("OLED SSD1306 — I2C/SPI",
 ["Буфер 1 КБ у RAM", "Сторінки GDDRAM", "I2C вистачає для тексту!"]),
"stm32-tft-lcd-scheme.png": ("TFT — SPI або FSMC",
 ["SPI: повільно, DMA!", "FSMC: паралельно швидко", "LTDC + SDRAM для великих"]),
"stm32-servo-rele-ws-scheme.png": ("Сервоприводи, реле, WS2812",
 ["Серво: 50 Гц, 1–2 мс", "Реле: транзистор + діод!", "WS2812: SPI+DMA як біти"]),
"stm32-nrf-lora-scheme.png": ("NRF24/LoRa — радіо по SPI",
 ["Труби і ACK у NRF", "LoRa: SF/BW/CR тріада", "Антена 50 Ом!"]),
"stm32-rs485-eth-scheme.png": ("RS485/CAN/Ethernet",
 ["DE-керування напрямом!", "Термінація 120 Ом", "Ethernet: PHY + RMII"]),
"stm32-gps-gsm-scheme.png": ("GPS/GSM — UART-модулі",
 ["NMEA 9600 + DMA-idle", "Живлення 2 А піки!", "Антена з видом на небо"]),
"stm32-bluepill-board-scheme.png": ("Blue Pill — карта плати",
 ["F103C8 + PC13-LED", "USB тільки живлення!", "BOOT0-перемичка + RESET"]),
"stm32-blackpill-board-scheme.png": ("Black Pill — карта плати",
 ["F401/F411 + USB-C!", "Кнопка NRST + BOOT0", "3.3V LDO з запасом"]),
"stm32-nucleo-board-scheme.png": ("Nucleo — карта плати",
 ["ST-Link + VCP з коробки!", "JP5: вибір живлення", "Morpho + Arduino-гребінки"]),
"stm32-discovery-board-scheme.png": ("Discovery — карта плати",
 ["Дисплей + сенсори з коробки", "Аудіо-ЦАП і MEMS!", "Демо-прошивка ST"]),
"stm32-modbus-scheme.png": ("Modbus — регістри і CRC",
 ["Адреса + функція + дані", "CRC16 в кінці!", "DE вчасно, інакше колізія"]),
"stm32-dfu-bootloader-scheme.png": ("DFU і IAP — оновлення",
 ["BOOT0=1: заводський loader", "IAP: стрибок в застосунок", "Два слоти = відкат!"]),
"stm32-security-scheme.png": ("Безпека — RDP і TrustZone",
 ["RDP-2 — назавжди!", "Secure boot ланцюжком", "WDT скрізь!"]),
"stm32-weather-station-scheme.png": ("Метеостанція — вузол",
 ["BME280 + RTC + сон", "LoRa/UART — наверх", "Батарея на роки!"]),
"stm32-gps-tracker-scheme.png": ("GPS-трекер — вузол",
 ["NMEA + DMA-idle", "GSM піки 2 А!", "Сон між точками"]),
"stm32-energy-monitor-scheme.png": ("Енергомонітор — вузол",
 ["Шунт + INA219", "True-RMS в АЦП", "Лог на SD-карту"]),
"stm32-lab-tools-scheme.png": ("Лабораторія — прилади",
 ["Мультиметр першим!", "Логічний аналізатор на шини", "SWV замість printf"]),
"stm32-pcb-montazh-scheme.png": ("Плата — проєкт і монтаж",
 ["Декуплінг біля VDD!", "Земля суцільним полігоном", "ST-Link роз'єм одразу!"]),
"stm32-faq-faq-scheme.png": ("FAQ — діагностика",
 ["Симптом → причина → фікс", "Міряй, не гадай!", "Мінімум коду для повтору"]),
"stm32-checklist-scheme.png": ("Чеклісти — запуск",
 ["Живлення → конект → Blink", "Кожен пункт галочкою", "Не працює — назад на крок"]),
"stm32-datasheet-links-scheme.png": ("Даташити — де шукати",
 ["st.com — першоджерело!", "AN2606 для bootloader", "Errata ДО плати!"]),
"stm32-dma-deepdive-scheme.png": ("DMA — режими і потоки",
 ["Circular: для аудіо/потоків", "Double Buffering: без розривів",
  "Periph-to-Periph: без CPU!", "FIFO + Burst: швидкий доступ"]),
"stm32-nvic-priority-scheme.png": ("NVIC — пріоритети і групування",
 ["Preemption: перебиває інше", "Subpriority: чекає в черзі",
  "Priority Grouping: 4/2/1/0", "Latency: Tail-chaining"]),
"stm32-perf-bench-scheme.png": ("Оптимізація — HAL vs LL vs Reg",
 ["DWT: підрахунок циклів", "Flash Wait States: вплив на швидкість",
  "Inlining: зменшення overhead", "CCM-RAM: найшвидша пам'ять"]),
"stm32-pcb-guidelines-scheme.png": ("Hardware Design — правила",
 ["Vcap біля ноги чипа!", "VDDA-VSSA: розділення",
  "HSE кварц: короткі шляхи", "Decoupling: 100нФ на кожен VDD"]),
"stm32-emi-emc-scheme.png": ("EMI/EMC — захист",
 ["TVS діод на вхід", "Ferrite bead на живлення",
  "Slew-rate: м'який фронт", "Земля: суцільний полігон"]),
"stm32-diag-map-scheme.png": ("Diagnostyka — instrumenty",
 ["Symptom, prylad, sygnal", "UART movchyt, analizator, baudrate", "I2C vysyt, ostsylograf, SCL"]),
"stm32-ble-wb-scheme.png": ("BLE на WB — сервіси",
 ["GATT: сервіси і характеристики", "Спочатку advertising, потім зєднання",
  "CCCD: підписка на notify", "MAC і калібрування в OTP"]),
"stm32-lorawan-wl-scheme.png": ("LoRaWAN на WL — класи",
 ["OTAA: приєднання перед даними", "Duty-cycle: паузи за законом!", "ADR: мережа керує SF",
  "Класи A/B/C: сон проти затримки"]),
"stm32-antena-50ohm-scheme.png": ("Антена 50 Ом — узгодження",
 ["Пі-ланцюг біля виводу", "Keepout: міді під антеною нема",
  "Вимір: VNA або RSSI на дистанції", "Сертифікат: з модулем простіше"]),
"stm32-flash-otp-scheme.png": ("Flash і OTP — память",
 ["Сторінки 2К: стирання сторінками", "OTP: запис назавжди!", "EEPROM: емуляція з вирівнюванням",
  "RDP закриває читання!"]),
"stm32-ext-loader-scheme.png": ("Зовнішні лоадери — QSPI",
 ["Лоадер: init QSPI перед прошивкою", "CubeProgrammer: додати файл лоадера",
  "XIP: код з QSPI напряму", "Verify завжди!"]),
"stm32-buck-boost-scheme.png": ("Buck і boost — живлення",
 ["Індуктивність під струм із запасом", "Петля звязку коротка",
  "Bulk на вході і виході", "ККД міряємо, а не віримо"]),
"stm32-level-shift-scheme.png": ("Рівні 5В і 3.3В — узгодження",
 ["Дільник тільки для входу!", "MOSFET: двонаправлений шлях", "Мікросхеми: TXS0108",
  "I2C: підтяжки з кожного боку"]),
"stm32-charger-protect-scheme.png": ("Заряд і захист — батарея",
 ["TP4056: CC і CV автоматично", "DW01: від перезаряду і короткого", "Термістор: стоп при перегріві",
  "Запобіжник: остання лінія"]),
"stm32-driver-template-scheme.png": ("Шаблон драйвера — шари",
 ["Init: перевірка звязку!", "Read: регістри в значення", "Колбеки: події наверх",
  "Помилки: коди, не мовчання"]),"stm32-freertos-scheme.png": ("FreeRTOS — задачі і черги",
 ["ISR: прапорець, не робота!", "Черга з ISR тільки FromISR", "Пріоритет NVIC нижче порога",
  "Стек задачі з запасом!"]),"stm32-lin-smbus-i3c-scheme.png": ("LIN SMBus I3C — другий рівень",
 ["LIN: UART плюс break!", "SMBus: I2C з таймаутами", "I3C: швидше і з перериваннями",
  "Починай з простого!"]),"stm32-pressure-scheme.png": ("Тиск — барометри",
 ["Температурна компенсація!", "Печера vs вулиця: герметизація", "Висота з формули, не з голови",
  "IIR-фільтр проти шуму вітру"]),
"stm32-co2-scheme.png": ("CO2 — повітря",
 ["Автокалібрування потребує провітрювання!", "MH-Z19: UART плюс ШІМ", "SCD40: тільки I2C",
  "Перші дні бреше — прогрів!"]),
"stm32-light-scheme.png": ("Світло — люкси",
 ["Діапазон: gain під задачу", "Скло ріже спектр!", "Інтеграція довша — точніше",
  "ІЧ-канал віднімаємо"]),
"stm32-rc522-scheme.png": ("RFID RC522 — 13.56 МГц",
 ["Живлення 3.3 В, не 5!", "Антена-котушка на платі", "UID читається, не захист!",
  "Mifare ключі не в коді!"]),"stm32-modbus-gateway-scheme.png": ("Modbus-шлюз — міст",
 ["RTU знизу, TCP наверх", "Карта регістрів єдина", "Черга запитів без колізій",
  "Лог помилок шини"]),
"stm32-usb-logger-scheme.png": ("USB-логер — запис",
 ["Дані в кільцевий буфер", "Скидання на флешку пачками", "CDC для живого перегляду",
  "Мітка часу з RTC"]),"stm32-epaper-scheme.png": ("E-paper — чорнила",
 ["Оновлення секунди, не мілісекунди!", "Часткове для цифр, повне від привидів",
  "Температура впливає на контраст", "LUT-таблиці з даташита!"]),
"stm32-lvgl-scheme.png": ("LVGL — графіка",
 ["Буфер: десята частина екрана", "Flush-колбек віддає на дисплей",
  "Тік 1 мс для анімацій", "Шрифти тільки потрібні!"]),"stm32-filesystem-scheme.png": ("Файли — LittleFS і FATFS",
 ["Пачками, не байтами!", "Sync перед сном", "Wear-leveling рівняє знос",
  "PVD рятує останній запис"]),"stm32-mq-gas-scheme.png": ("MQ-гази — прогрів",
 ["Прогрів 24+ годин перед калібруванням!", "Нагрівач їсть міліампери", "Ro чисте повітря — опора",
  "Пороги, не ppm!"]),
"stm32-encoder-scheme.png": ("Енкодер — імпульси",
 ["Таймер в encoder-режимі!", "A/B зі зсувом 90 градусів", "Z-мітка раз на оберт",
  "Фільтр дребезгу залізом"]),
"stm32-mqtt-scheme.png": ("MQTT — публікації",
 ["QoS 0/1/2: швидкість проти гарантії", "LWT: заповіт на розрив", "Keep-alive тримає NAT",
  "TLS їсть RAM — рахуй!"]),"stm32-maketka-scheme.png": ("Макетка — межі",
 ["I2C коротко і повільно!", "SWD: короткі дроти", "VDDA окремо від цифри",
  "Далі — паяна плата!"]),"stm32-w5500-scheme.png": ("W5500 — Ethernet по SPI",
 ["SPI 40+ МГц, коротко!", "RST і INT вивести", "Сокети: 8 апаратних",
  "MAC з OTP або прошивки!"]),"stm32-sim7600-scheme.png": ("SIM7600 — LTE модем",
 ["Живлення 2 А піки!", "AT: повільно і з таймаутом", "MQTT всередині модема!",
  "Антена подалі від цифри"]),"stm32-lora-p2p-scheme.png": ("LoRa P2P — без мережі",
 ["Обидва боки однакові: SF/BW/CR!", "Синхрослово своє, не WAN!", "ACK вручну, повторів мало",
  "Ефір спільний — слухай перед TX!"]),"stm32-shunt-opamp-scheme.png": ("Шунт і ОУ — вимір струму",
 ["Кельвін: sense окремо!", "Шунт малий, підсилення велике", "Потужність шунта рахуємо!",
  "Фільтр проти ШІМ-дзвону"]),"stm32-f7-scheme.png": ("F7 — міст між F4 і H7",
 ["M7 216 МГц + FPU подвійна!", "ART і кеші як у H7", "Камера і LTDC як у F4",
  "Бери H7 для нового!"]),"stm32-weact-board-scheme.png": ("WeAct — міні-плати",
 ["USB-C з даними!", "Кнопки NRST і BOOT0", "Перевір ревізію плати!",
  "Приклади WeAct на GitHub"]),"nucleo-morpho-scheme.png": ("Nucleo-64 — Morpho + ST-Link",
 ["ST-Link (вбудований!) ──► USB ПК", "SWD + VCP в одному",
  "JP5: U5V / E5V / VIN — вибрати живлення!", "Morpho-піни: Arduino-сумісні + додаткові",
  "NRST кнопка + BOOT0 перемичка"]),
"stm32-drone-scheme.png": ("STM32-дрон: FC і ESC",
 ["Rate-ПІД в ISR 1 кГц — без malloc!",
  "DShot300: TIM PSC=141, ARR=3, CCR=2",
  "ICM-20948 SPI: I2C не встигає",
  "Failsafe: втрата RC > 500 мс → стоп",
  "BEC 5 В 3 А окремо від моторів!",
  "Тюнінг: air-mode на столі, без моторів"]),
"stm32-power-scheme.png": ("STM32-живлення: розрахунок",
 ["I > 200 мА з 5 В → buck, не LDO!",
  "SY8113: L 2.2 мкГн, COUT 22 мкФ + 100 нФ",
  "VDDA: окремий LDO 1.8 В + ферит",
  "4×100 нФ біля кристалу, bulk 100 мкФ",
  "GND-петля: L і COUT максимально близько",
  "BOR-порог: вимірюємо просадки!"]),
"stm32-stepper-scheme.png": ("Крок STM32: три рівні",
 ["L298N: 1/1 крок, 5 В логіка, гучний",
  "A4988: до 1/32, TIM STEP/DIR",
  "TMC2209: UART, до 1/256, StealthChop",
  "RSEN: 0.11 Ом → ~1.2 А, 0.15 → ~0.9 А",
  "Контур: енкодер TIM-ENC → викинуті кроки",
  "Трапеція: a по моменту, без прослизання"]),
"stm32-wifi-esp-at-scheme.png": ("STM32 + ESP-AT: WiFi-модем",
 ["ESP8266/ESP32 з прошивкою ESP-AT",
  "UART 115200, TX/RX перехресно",
  "Живлення 3.3 В 1 А + 470 мкФ!",
  "AT+CWJAP, AT+MQTTPUB команди",
  "Прийом через DMA, не в IRQ",
  "WDT + реконект кожні 60 с"]),
"stm32-ble-hc05-hm10-scheme.png": ("HC-05 / HM-10: SPP проти BLE",
 ["HC-05: прозорий COM-міст, 38400 в AT",
  "HM-10: GATT FFE0/FFE1, пакети 20 Б",
  "KEY в HIGH до живлення = AT-режим",
  "HM-10 без знака рівності в команді!",
  "iPhone: тільки HM-10, не HC-05",
  "STATE-пин веде на світлодіод"]),
"stm32-strum-power-scheme.png": ("Струм і потужність: три рівні",
 ["ACS712: Холл у розриві, нуль = VCC/2",
  "Версії 5/20/30 А: 185/100/66 мВ/А",
  "INA226: шунт + I2C, точність 0.1 %",
  "PZEM-004T: 220 В тільки через CT!",
  "Усереднення 64, викинути min/max",
  "Калібрування нуля — в EEPROM"]),
"stm32-air-quality-scheme.png": ("Якість повітря: пил + VOC",
 ["PMS5003: кадр 42 4D, сума завжди!",
  "SPS30: bins + автопочистка",
  "SGP40: потрібні RH/T з BME280!",
  "VOC-індекс 100 = чисте повітря",
  "Будити раз на 5 хв, 30 с прогрів",
  "RH > 85 %: дані пилу сумнівні"]),
"stm32-max7219-tm1637-scheme.png": ("MAX7219 / TM1637 індикація",
 ["MAX7219: SPI, регістри 0x09-0x0C",
  "Каскад DOUT→DIN, LOAD в кінці",
  "RSET 20-30 кОм для табло",
  "TM1637: CLK+DIO bit-bang",
  "Пік струму 8x8x20 мА: рахуй БЖ!",
  "Shutdown 0x01, інакше темно"]),
"stm32-audio-dfplayer-scheme.png": ("DFPlayer + I2S звук",
 ["DFPlayer: UART 9600, файли 0001.mp3",
  "SPK мінус НЕ земля, міст!",
  "BUSY читати перед кожним пуском",
  "Папка 0x0E: вставка поверх музики",
  "5 В 1 А окремо + 1000 мкФ",
  "I2S + DMA: музика без CPU"]),
"stm32-iot-discovery-scheme.png": ("B-L475E-IOT01A вузол",
 ["L475 + WiFi/BLE/Sub-GHz/NFC",
  "HTS221+LPS22HB+LSM6DSL на борту",
  "VL53L0X + 2 мікрофони PDM",
  "ST-Link V2-1: прошивка по USB",
  "Arduino + PMOD для розширення",
  "Stop 2: місяці від батарейки"]),
"stm32-mag-gesture-rtc-scheme.png": ("Компас + жести + RTC",
 ["QMC5883L 0x0D: вісімка для нуля",
  "Tilt-компенсація, інакше ±30 градусів",
  "APDS-9960: скло тільки ІЧ-прозоре",
  "DS3231: BCD + батарейка CR2032",
  "0x68 конфлікт: розвести AD0!",
  "9-DOF + GPS = повна навігація"]),
"stm32-canopen-scheme.png": ("CANopen: словник і сервіси",
 ["NodeID перемичками, швидкість єдина!",
  "Heartbeat завжди увімкнений",
  "SDO — параметри, PDO — дані",
  "Мапи зберегти в EDS!",
  "Термінатори 120 Ом на кінцях"]),
"stm32-foc-bldc-scheme.png": ("FOC: векторне керування",
 ["Id=0, Iq=момент — філософія!",
  "Dead-time 1-2 мкс святий",
  "Петля струму 20 кГц в IRQ",
  "Калібрування фаз першим",
  "Старт з open-loop"]),
"stm32-h7-deep-scheme.png": ("H7: кеші і швидкість",
 ["Кеші + MPU — день перший!",
  "SDRAM: clean/invalidate DMA",
  "VCAP-конденсатори обов'язково!",
  "VOS за навантаженням",
  "FMC-таймінги з CubeMX"]),
"stm32-u5-deep-scheme.png": ("U5: мікроампери і TrustZone",
 ["ID-джампер: виміряти струм!",
  "Stop 1 — золота середина",
  "Тактування відновити після сну",
  "Ключі в сейфі, не в git",
  "Цикл: вимір → TX → сон"]),
"stm32-usb-c-pd-scheme.png": ("USB-C PD: домовлені вати",
 ["Профіль = пік + 30%!",
  "Навантаження після контракту",
  "TVS + запобіжник на VBUS",
  "Fallback 5V завжди",
  "Кабель — частина системи"]),
"stm32-secure-boot-scheme.png": ("Secure Boot: ланцюг довіри",
 ["RDP 2 — останнім кроком!",
  "A/B-слоти + відкат",
  "Версія тільки вперед",
  "Ключі в HSM/сейфі",
  "Тампер-піни підтягнути"]),
"stm32-dcmi-camera-scheme.png": ("DCMI: камера на STM32",
 ["Ядро 1.8V живити першим!",
  "XCLK 24 МГц з MCO",
  "ID-читання — сенсор живий",
  "QVGA для старту",
  "Мапінг з даташита чипа!"]),
"stm32-lwip-ethernet-scheme.png": ("LWIP: провід без ОС",
 ["RMII-піни з AF-таблиці!",
  "Статика надійніша за DHCP",
  "Сокети закривати завжди",
  "memp-пули під задачу",
  "Радіо — резерв, не основа"]),
}
def draw(name, title, lines):
    Ft, Fs, Fm, Ff = fonts()
    W, H = 1000, 200 + len(lines) * 44 + 120
    H = max(H, 520)
    img = Image.new("RGB", (W, H), "white")
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, W, 130], fill=(17, 42, 67))
    d.text((30, 22), "STM32-Reference", font=Fs, fill=(125, 211, 252))
    d.text((30, 55), title, font=Ft, fill="white")
    y = 150
    d.rectangle([0, y - 34, W, y + 2], fill=(255, 251, 235))
    d.text((30, y - 30), "3.3V logika! 5V tilky na FT-pinah za datasheetom.", font=Ff, fill=(146, 64, 14))
    y += 30
    for ln in lines:
        d.text((30, y), "•  " + ln, font=Fm, fill=(17, 24, 39))
        y += 44
    d.rectangle([0, H - 56, W, H], fill=(241, 245, 249))
    d.text((30, H - 42), "STM32-Reference  •  zgenerovano lokalno (bez kopiiovanykh kartynok)",
           font=Ff, fill=(100, 116, 139))
    img.save(os.path.join(OUT, name))

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for n, (t, ls) in C.items():
        draw(n, t, ls)
    print(f"generated {len(C)} png")